// packages/_private/vue-demo/src/DemosTemplate.vue
<script setup lang="ts">
import { SynVueTab, SynVueTabGroup, SynVueTabPanel } from '@synergy-design-system/vue';
import type { SynTabShowEvent } from '@synergy-design-system/components';
import { type Component } from 'vue';

import { computed } from 'vue';
const props = defineProps<{ demos: [string, Component][] }>();
const demos = computed(() => props.demos);

const activeDemo = computed( () => demos.value[0]?.[0] || '');

const showTab = (e: SynTabShowEvent) => {
  const { name } = e.detail;
  (e.target as HTMLElement).parentElement?.scrollTo(0, 0);

  const dialog = document.querySelector('syn-dialog');
  if (dialog) {
    dialog.open = name === 'Dialog';
  }
};
</script>

<template>
  <span v-if="demos.length === 0">
    There are no demos available.
  </span>

  <SynVueTabGroup
    class="demo-tab-group"
    @syn-tab-show="showTab"
    placement="end"
    v-else
  >
    <template
      v-for="([name, Component]) in demos"
      :key="name"
    >
      <SynVueTab
        :active="name === activeDemo"
        :id="`tab-${name}`"
        :panel="name as string"
        slot="nav"
      >
        {{name}}
      </SynVueTab>
      <SynVueTabPanel
        :active="name === activeDemo"
        :name="name as string"
      >
        <div :id="`tab-content-${name}`" style="display: 'contents';">
          <component :is="Component" />
        </div>
      </SynVueTabPanel>
    </template>
  </SynVueTabGroup>
</template>

// packages/_private/react-demo/src/DemosTemplate.tsx
import * as React from 'react';

export type DemosTemplateProps = {
  demos: Array<[string, () => React.JSX.Element]>;
};

export const DemosTemplate = ({ demos }: DemosTemplateProps) => {
  const activeDemo = demos[0]?.[0] || '';

  if (demos.length === 0) {
    return (
      <span>There are no demos available.</span>
    );
  }

  return (
    <syn-tab-group
      className="demo-tab-group"
      onsyn-tab-show={(e) => {
        const { name } = e.detail;
        (e.target as HTMLElement).parentElement?.scrollTo(0, 0);

        const dialog = document.querySelector('syn-dialog');
        if (dialog) {
          dialog.open = name === 'Dialog';
        }
      }}
      placement='end'
    >
      {demos.map(([name, Component]) => (
        <React.Fragment key={name}>
          <syn-tab
            active={name === activeDemo}
            id={`tab-${name}`}
            panel={name}
            slot="nav"
          >
            {name}
          </syn-tab>
          <syn-tab-panel
            active={name === activeDemo}
            name={name}
          >
            <div id={`tab-content-${name}`}>
              <Component />
            </div>
          </syn-tab-panel>
        </React.Fragment>
      ))}
    </syn-tab-group>
  );
};
