// packages/_private/angular-demo/src/demoform/demoform.component.ts
import type { SynChangeEvent } from '@synergy-design-system/components';
import { highlightOptionRenderer, serialize } from '@synergy-design-system/components';
import { Component, ElementRef, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import {
  type FormStatus,
  currencyNumberFormatter,
  mockData,
  statusError,
  statusSuccess,
  statusWarning,
} from '@synergy-design-system/demo-utilities';

const initialData = mockData('initialFullFormData');

@Component({
  selector: 'demo-form',
  standalone: false,
  styleUrls: ['./demoform.component.css'],
  templateUrl: './demoform.component.html',
})
export class DemoForm {

  @ViewChild('form') form!: ElementRef<HTMLFormElement>;

  formData!: FormGroup;

  formStatus: FormStatus = statusWarning;

  nationalities = mockData('nationalities');

  highlightOptionRenderer = highlightOptionRenderer;

  formatter = currencyNumberFormatter;

  private _initFormData() {
    this.formData = this.fb.group({
      ...initialData,
    });
  }

  constructor(private fb: FormBuilder) {
    this._initFormData();
  }

  reset() {
    this.formStatus = statusWarning;
    this._initFormData();
  }

  submit(form: FormGroup) {
    const isValid = form.valid;
    this.formStatus = isValid ? statusSuccess : statusError;
  }

  synChange(_: SynChangeEvent) {
    const form = this.form.nativeElement;

    const normalizedData = serialize(form);

    // Log the normalized data
    console.log(normalizedData);
  }

  currencyFormatter = (value: number) => {
    return this.formatter.format(value);
  }
}

<form
  enctype="multipart/form-data"
  [formGroup]="formData"
  (reset)="reset()"
  (ngSubmit)="submit(formData)"
  (syn-change)="synChange($event)"
  #form
  ngNativeValidate
>
  @if (formStatus.type !== 'warning') {
    <syn-alert
      class="form-validation-message"
      [open]="true"
      [variant]="formStatus.type"
    >
      <syn-icon slot="icon" [name]="formStatus.icon" />
      {{ formStatus.message }}
    </syn-alert>
  }

  <!-- PersonalInformation -->
  <syn-fieldset legend="Personal Information">

    <syn-radio-group
      formControlName="gender"
      id="radiogroup-gender"
      name="gender"
      label="Please tell us your gender"
      required
    >
      <syn-radio value="f">Female</syn-radio>
      <syn-radio value="m">Male</syn-radio>
      <syn-radio value="other">Other</syn-radio>
    </syn-radio-group>

    <syn-select
      formControlName="role"
      id="select-role"
      label="Current position"
      name="role"
      required
    >
      <syn-optgroup label="Developers">
        <syn-option value="backend">Backend Developer</syn-option>
        <syn-option value="frontend">Frontend Developer</syn-option>
      </syn-optgroup>
      <syn-optgroup label="Other">
        <syn-option value="lead">Team Lead</syn-option>
        <syn-option value="other">Other (please specify in comment section below)</syn-option>
      </syn-optgroup>
    </syn-select>

    <syn-input
      formControlName="name"
      id="input-text"
      label="Name"
      [minlength]="5"
      [maxlength]="20"
      name="name"
      placeholder="Please insert a value for the regular text input (between 5 and 20 Characters)"
      required
      type="text"
    />

    <syn-input
      formControlName="email"
      id="input-email"
      label="E-Mail"
      name="email"
      placeholder="Please insert your E-mail address"
      required
      type="email"
    />

    <syn-input
      formControlName="phone"
      id="input-phone"
      label="Phone"
      name="phone"
      placeholder="Please provide your phone number"
      required
      type="tel"
    />

    <syn-input
      formControlName="date"
      id="input-date"
      label="Date of birth"
      name="date"
      type="date"
    />

    <syn-combobox
      formControlName="nationality"
      id="input-nationality"
      label="Nationality"
      name="nationality"
      required
      [getOption]="highlightOptionRenderer"
    >
      @for (nationality of nationalities; track nationality) {
        <syn-option>{{nationality}}</syn-option>
      }
    </syn-combobox>

  </syn-fieldset>
  <!-- /PersonalInformation -->

  <syn-divider />

  <!-- Security -->
  <syn-fieldset legend="Security">
    <syn-input
      formControlName="password"
      id="input-password"
      label="Provide a secure password"
      name="password"
      password-toggle
      pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
      placeholder="Please provide at least one uppercase and lowercase letter and a number"
      type="password"
    />

    <syn-input
      formControlName="code"
      id="input-number"
      label="Please provide a fallback numeric value that may be used for password recovery"
      min="1000"
      max="9999"
      name="code"
      placeholder="Please choose a value with four digits, e.g. 1234"
      type="number"
    />
  </syn-fieldset>
  <!-- /Security -->

  <syn-divider />

  <!-- Topics -->
  <syn-fieldset legend="Topics">
    <syn-select
      clearable
      formControlName="topics"
      id="topics"
      label="I am interested in the following technologies"
      multiple
      name="topics"
    >
      <syn-optgroup label="Frontend">
        <syn-option value="angular">Angular</syn-option>
        <syn-option value="react">React.js</syn-option>
        <syn-option value="vanilla">Vanilla.js</syn-option>
        <syn-option value="vue">Vue</syn-option>
      </syn-optgroup>
      <syn-optgroup label="Backend">
        <syn-option value="node">Node.js</syn-option>
        <syn-option value="Python">Python</syn-option>
      </syn-optgroup>
    </syn-select>

    <syn-combobox
      formControlName="testing"
      id="testing-frameworks"
      label="Which testing frameworks do you use?"
      multiple
      name="testing"
      placeholder="Select testing frameworks"
      [getOption]="highlightOptionRenderer"
      required
    >
      @for (framework of testingFrameworks; track framework.value) {
        <syn-option [value]="framework.value">{{framework.label}}</syn-option>
      }
    </syn-combobox>
  </syn-fieldset>
  <!-- /Topics -->

  <syn-divider />

  <!-- Happiness -->
  <syn-fieldset id="happiness-fields" legend="Happiness">
    <syn-range
      formControlName="happiness"
      id="happiness"
      label="How happy are you with the Synergy Design System?"
      [max]=10
      [min]=0
      name="happiness"
    >
      <nav slot="ticks">
        <syn-range-tick>🤮</syn-range-tick>
        <syn-range-tick>🥱</syn-range-tick>
        <syn-range-tick>😍</syn-range-tick>
      </nav>
    </syn-range>

    <syn-range
      formControlName="donations"
      id="donations"
      label="I would donate between"
      [max]="6000"
      [min]="0"
      name="donations"
      restrictMovement
      [tooltipFormatter]="currencyFormatter"
    >
      <nav slot="ticks">
        <syn-range-tick>0 €</syn-range-tick>
        <syn-range-tick>6.000 €</syn-range-tick>
      </nav>
    </syn-range>
  </syn-fieldset>
  <!-- /.Happiness -->

  <syn-divider />

  <!-- Experience -->
  <syn-fieldset legend="Experience">
    <syn-radio-group
      formControlName="experience"
      id="experience"
      label="How experienced are you with the Synergy Design System?"
      name="experience"
    >
      <syn-radio [value]=0>I have never used it</syn-radio>
      <syn-radio [value]=1 id="experience-little">I have used it a little</syn-radio>
      <syn-radio [value]=2>I have used it a lot</syn-radio>
      <syn-radio [value]=3>I am a Synergy Design System expert</syn-radio>
      <syn-radio [value]=4>I am the creator of the Synergy Design System</syn-radio>
    </syn-radio-group>
  </syn-fieldset>
  <!-- Experience -->

  <syn-divider />

  <!-- Marketing -->
  <syn-fieldset legend="Please inform me about the following technologies">
    <syn-checkbox
      formControlName="newsletterStandard"
      id="checkbox-newsletter-default"
      name="newsletterStandard"
    >
      Please subscribe me to the synergy newsletter
    </syn-checkbox>
    <syn-checkbox
      checked
      formControlName="newsletterUI"
      id="checkbox-newsletter-ui"
      name="newsletterUI"
      readonly
    >
      Please subscribe me to the synergy UI newsletter
    </syn-checkbox>
    <syn-checkbox
      formControlName="newsletterAngular"
      id="checkbox-newsletter-angular"
      name="newsletterAngular"
    >
      Please subscribe me to all things related to angular
    </syn-checkbox>
    <syn-checkbox
      formControlName="newsletterReact"
      id="checkbox-newsletter-react"
      name="newsletterReact"
    >
      Please subscribe me to all things related to react
    </syn-checkbox>
    <syn-checkbox
      formControlName="newsletterVanilla"
      id="checkbox-newsletter-vanilla"
      name="newsletterVanilla"
    >
      Please subscribe me to all things related to vanilla.js
    </syn-checkbox>
    <syn-checkbox
      formControlName="newsletterVue"
      id="checkbox-newsletter-vue"
      name="newsletterVue"
    >
      Please subscribe me to all things related to vue
    </syn-checkbox>
    <syn-switch
      formControlName="newsletterBeta"
      id="checkbox-newsletter-beta"
      name="newsletterBeta"
    >
      I am interested in the Synergy Beta Program
    </syn-switch>
    <syn-switch
      formControlName="newsletterUX"
      id="checkbox-newsletter-ux"
      name="newsletterUX"
      readonly
    >
      I am interested in the Synergy UX Program
    </syn-switch>
  </syn-fieldset>
  <!-- /Marketing -->

  <syn-divider />

  <!-- AdditionalInformation -->
  <syn-fieldset legend="Additional Information">
    <syn-textarea
      id="additional-info"
      formControlName="comment"
      label="Comment"
      name="comment"
      placeholder="Please provide additional information that might be helpful for your inquiry"
      [rows]="10"
    />
    <syn-file
      accept="image/*"
      droparea
      formControlName="files"
      help-text="Please upload images only"
      id="screenshot"
      label="Optional Screenshot(s)"
      multiple
      name="files"
    />
  </syn-fieldset>
  <!-- /AdditionalInformation -->

  <syn-divider />

  <!-- Actions -->
  <div class="syn-submit-buttons">
    <syn-button variant="outline" type="reset">Reset</syn-button>
    <syn-button variant="filled" type="submit">Send</syn-button>
  </div>
  <!-- /Actions -->

</form>

// packages/_private/react-demo/src/DemoForm.tsx
/* eslint-disable no-console */
import { useEffect, useRef, useState } from 'react';
import { highlightOptionRenderer, serialize } from '@synergy-design-system/components';
import {
  type FormStatus,
  currencyNumberFormatter,
  mockData,
  statusError,
  statusSuccess,
  statusWarning,
} from '@synergy-design-system/demo-utilities';
import type {
  SynChangeEvent,
  SynCheckbox,
  SynFile,
} from '@synergy-design-system/components';

type FormEnabledElements = HTMLElement & {
  checked?: boolean;
  name: string;
  value?: string;
};

const initialFormData = mockData('initialFullFormData');
const testingFrameworks = mockData('testingFrameworks');

export const DemoForm = () => {
  const formRef = useRef<HTMLFormElement>(null);
  const [formData, setFormData] = useState(initialFormData);
  const [formStatus, setFormStatus] = useState<FormStatus>(statusWarning);

  // This is needed, as synergy does its event with `syn-` prefix
  // and react wont let us bind arbitrary custom events :(
  useEffect(() => {
    const form = formRef.current;

    const listener = (e: SynChangeEvent) => {
      const normalizedData = serialize(form as HTMLFormElement);

      // Log the normalized data
      console.log(normalizedData);

      // Set the field into state
      const element = e.target as FormEnabledElements;
      const { name, value } = element;

      let finalValue;

      switch (element.tagName.toLocaleLowerCase()) {
        case 'syn-checkbox':
        case 'syn-switch':
          finalValue = (element as SynCheckbox).checked;
          break;
        case 'syn-file': finalValue = (element as SynFile).files; break;
        default: finalValue = value;
      }

      setFormData((curr) => ({
        ...curr,
        [name]: finalValue,
      }));
    };

    form?.addEventListener('syn-change', listener);
    return () => {
      form?.removeEventListener('syn-change', listener);
    };
  }, []);

  return (
    <form
      encType="multipart/form-data"
      method="post"
      onReset={() => {
        setFormStatus(statusWarning);
        setFormData(initialFormData);
      }}
      onSubmit={e => {
        e.preventDefault();
        e.stopPropagation();

        const formElement = e.target;
        const isValid = formElement.checkValidity();

        setFormStatus(isValid ? statusSuccess : statusError);
      }}
      ref={formRef}
    >
      {formStatus.type !== 'warning' && (
        <syn-alert
          className="form-validation-message"
          open
          variant={formStatus.type}
        >
          <syn-icon slot="icon" name={formStatus.icon} />
          {formStatus.message}
        </syn-alert>
      )}

      {/* PersonalInformation */}
      <syn-fieldset legend="Personal Information">

        <syn-radio-group
          id="radiogroup-gender"
          name="gender"
          label="Please tell us your gender"
          required
          value={formData.gender}
        >
          <syn-radio value="f">Female</syn-radio>
          <syn-radio value="m">Male</syn-radio>
          <syn-radio value="other">Other</syn-radio>
        </syn-radio-group>

        <syn-select
          id="select-role"
          label="Current position"
          name="role"
          required
          value={formData.role}
        >
          <syn-optgroup label="Developers">
            <syn-option value="backend">Backend Developer</syn-option>
            <syn-option value="frontend">Frontend Developer</syn-option>
          </syn-optgroup>
          <syn-optgroup label="Other">
            <syn-option value="lead">Team Lead</syn-option>
            <syn-option value="other">Other (please specify in comment section below)</syn-option>
          </syn-optgroup>
        </syn-select>

        <syn-input
          id="input-text"
          label="Name"
          minlength={5}
          maxlength={20}
          name="name"
          placeholder="Please insert a value for the regular text input (between 5 and 20 Characters)"
          required
          value={formData.name}
          type="text"
        />

        <syn-input
          id="input-email"
          label="E-Mail"
          name="email"
          placeholder="Please insert your E-mail address"
          required
          value={formData.email}
          type="email"
        />

        <syn-input
          id="input-phone"
          label="Phone"
          name="phone"
          placeholder="Please provide your phone number"
          required
          value={formData.phone}
          type="tel"
        />

        <syn-input
          id="input-date"
          label="Date of birth"
          name="date"
          value={formData.date}
          type="date"
        />

        <syn-combobox
          id="input-nationality"
          label="Nationality"
          name="nationality"
          required
          value={formData.nationality}
          placeholder='Please choose your nationality'
          getOption={highlightOptionRenderer}
        >
          {mockData('nationalities').map(n => (
            <syn-option key={n}>
              {n}
            </syn-option>
          ))}
        </syn-combobox>

      </syn-fieldset>
      {/* /PersonalInformation */}

      <syn-divider />

      {/* Security */}
      <syn-fieldset legend="Security">
        <syn-input
          id="input-password"
          label="Provide a secure password"
          name="password"
          password-toggle
          pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
          placeholder="Please provide at least one uppercase and lowercase letter and a number"
          required
          type="password"
          value={formData.password}
        />

        <syn-input
          id="input-number"
          label="Please provide a fallback numeric value that may be used for password recovery"
          min="1000"
          max="9999"
          name="code"
          placeholder="Please choose a value with four digits, e.g. 1234"
          type="number"
          value={formData.code}
        />
      </syn-fieldset>
      {/* /Security */}

      <syn-divider />

      {/* Topics */}
      <syn-fieldset legend="Topics">
        <syn-select
          clearable
          id="topics"
          label="I am interested in the following technologies"
          multiple
          name="topics"
          value={formData.topics}
        >
          <syn-optgroup label="Frontend">
            <syn-option value="angular">Angular</syn-option>
            <syn-option value="react">React.js</syn-option>
            <syn-option value="vanilla">Vanilla.js</syn-option>
            <syn-option value="vue">Vue</syn-option>
          </syn-optgroup>
          <syn-optgroup label="Backend">
            <syn-option value="node">Node.js</syn-option>
            <syn-option value="Python">Python</syn-option>
          </syn-optgroup>
        </syn-select>

        <syn-combobox
          id="testing-frameworks"
          label="Which testing frameworks do you use?"
          multiple
          name="testing"
          placeholder="Select testing frameworks"
          value={formData.testing}
          getOption={highlightOptionRenderer}
          required
        >
          {testingFrameworks.map((framework) => (
            <syn-option key={framework.value} value={framework.value}>
              {framework.label}
            </syn-option>
          ))}
        </syn-combobox>
      </syn-fieldset>
      {/* /Topics */}

      <syn-divider />

      {/* Happiness */}
      <syn-fieldset id="happiness-fields" legend="Happiness">
        <syn-range
          id="happiness"
          label="How happy are you with the Synergy Design System?"
          max={10}
          min={0}
          name="happiness"
          value={formData.happiness}
        >
          <nav slot="ticks">
            <syn-range-tick>🤮</syn-range-tick>
            <syn-range-tick>🥱</syn-range-tick>
            <syn-range-tick>😍</syn-range-tick>
          </nav>
        </syn-range>

        <syn-range
          id="donations"
          label="I would donate between"
          max={6000}
          min={0}
          name="donations"
          restrict-movement
          tooltipFormatter={value => currencyNumberFormatter.format(value)}
          value={formData.donations}
        >
          <nav slot="ticks">
            <syn-range-tick>0 €</syn-range-tick>
            <syn-range-tick>6.000 €</syn-range-tick>
          </nav>
        </syn-range>

      </syn-fieldset>
      {/* /Happiness */}

      <syn-divider />

      {/* Experience */}
      <syn-fieldset legend="Experience">
        <syn-radio-group
          id="experience"
          label="How experienced are you with the Synergy Design System?"
          name="experience"
          value={formData.experience}
        >
          <syn-radio value={0}>I have never used it</syn-radio>
          <syn-radio value={1} id="experience-little">I have used it a little</syn-radio>
          <syn-radio value={2}>I have used it a lot</syn-radio>
          <syn-radio value={3}>I am a Synergy Design System expert</syn-radio>
          <syn-radio value={4}>I am the creator of the Synergy Design System</syn-radio>
        </syn-radio-group>
      </syn-fieldset>
      {/* /Experience */}

      <syn-divider />

      {/* Marketing */}
      <syn-fieldset legend="Please inform me about the following technologies">
        <syn-checkbox
          checked={formData.newsletterStandard}
          id="checkbox-newsletter-default"
          name="newsletterStandard"
        >
          Please subscribe me to the synergy newsletter
        </syn-checkbox>
        <syn-checkbox
          checked={formData.newsletterUI}
          readonly
          id="checkbox-newsletter-ui"
          name="newsletterUI"
        >
          Please subscribe me to the synergy UI newsletter
        </syn-checkbox>
        <syn-checkbox
          checked={formData.newsletterAngular}
          id="checkbox-newsletter-angular"
          name="newsletterAngular"
        >
          Please subscribe me to all things related to angular
        </syn-checkbox>
        <syn-checkbox
          checked={formData.newsletterReact}
          id="checkbox-newsletter-react"
          name="newsletterReact"
        >
          Please subscribe me to all things related to react
        </syn-checkbox>
        <syn-checkbox
          checked={formData.newsletterVanilla}
          id="checkbox-newsletter-vanilla"
          name="newsletterVanilla"
        >
          Please subscribe me to all things related to vanilla.js
        </syn-checkbox>
        <syn-checkbox
          checked={formData.newsletterVue}
          id="checkbox-newsletter-vue"
          name="newsletterVue"
        >
          Please subscribe me to all things related to vue
        </syn-checkbox>
        <syn-switch
          checked={formData.newsletterBeta}
          id="checkbox-newsletter-beta"
          name="newsletterBeta"
        >
          I am interested in the Synergy Beta Program
        </syn-switch>
        <syn-switch
          checked={formData.newsletterUX}
          id="checkbox-newsletter-ux"
          name="newsletterUX"
          readonly
        >
          I am interested in the Synergy UX Program
        </syn-switch>

        <syn-radio-group
          id="preferred-contact-method"
          label="Preferred contact method"
          name="preferredContactMethod"
          value={formData.preferredContactMethod}
        >
          <syn-radio-button value="email">E-Mail</syn-radio-button>
          <syn-radio-button value="phone" readonly>Phone</syn-radio-button>
          <syn-radio-button value="other">Other</syn-radio-button>
        </syn-radio-group>
      </syn-fieldset>
      {/* /Marketing */}

      <syn-divider />

      { /* AdditionalInformation */ }
      <syn-fieldset legend="Additional Information">
        <syn-textarea
          id="additional-info"
          label="Comment"
          name="comment"
          placeholder="Please provide additional information that might be helpful for your inquiry"
          rows={10}
        >
          {formData.comment}
        </syn-textarea>
        <syn-file
          accept="image/*"
          droparea
          help-text="Please upload images only"
          files={formData.files}
          id="screenshot"
          label="Optional Screenshot(s)"
          multiple
          name="files"
        />
      </syn-fieldset>

      { /* /AdditionalInformation */ }

      <syn-divider />

      {/* Actions */}
      <div className="syn-submit-buttons">
        <syn-button variant="outline" type="reset">Reset</syn-button>
        <syn-button variant="filled" type="submit">Send</syn-button>
      </div>
      {/* /Actions */}

    </form>
  );
};
