// packages/_private/angular-demo/src/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'home',
  styleUrls: ['./home.styles.css'],
  templateUrl: './home.component.html',
})
export class Home {

}

<h1 class="syn-heading--3x-large">
  Welcome to the Synergy Angular Demo!
</h1>

<p class="syn-body--medium">
  In this demo some use cases and our components are tested in the Angular ecosystem,
  like navigation handling, forms and theme switching.
</p>

// packages/_private/react-demo/src/Home.tsx
import type { FC } from 'react';

export const Home: FC = () => (
  <>
    <h1 className="syn-heading-3x-large">
      Welcome to the Synergy React Demo!
    </h1>
    <p className="syn-body-medium">
      In this demo some use cases and our components are tested in the react ecosystem,
      like navigation handling, forms and theme switching.
    </p>
  </>
);
