// packages/_private/angular-demo/src/sizeswitch/sizeswitch.component.ts
import { Component } from '@angular/core';
import { SynergyComponentsModule } from '@synergy-design-system/angular';
import {
  type AllowedSizes,
  setGlobalSize,
} from '@synergy-design-system/demo-utilities';

@Component({
  imports: [SynergyComponentsModule],
  selector: 'size-switch',
  standalone: true,
  templateUrl: './sizeswitch.component.html',
})
export class SizeSwitchComponent {
  currentSize: AllowedSizes = 'medium';

  switchSize(size: AllowedSizes) {
    setGlobalSize(size);
    this.currentSize = size;
  }
}

<syn-button-group>
  <syn-tooltip content="Set element size to small">
    <syn-icon-button
      [color]="currentSize === 'small' ? 'primary' : 'currentColor'"
      data-size="small"
      name="density_small"
      label="Set element size to small"
      size="small"
      (click)="switchSize('small')"
    />
  </syn-tooltip>
  <syn-tooltip content="Set element size to medium">
    <syn-icon-button
      [color]="currentSize === 'medium' ? 'primary' : 'currentColor'"
      data-size="medium"
      name="density_medium"
      label="Set element size to medium"
      size="small"
      (click)="switchSize('medium')"
    />
  </syn-tooltip>
  <syn-tooltip content="Set element size to large">
    <syn-icon-button
      [color]="currentSize === 'large' ? 'primary' : 'currentColor'"
      data-size="large"
      name="density_large"
      label="Set element size to large"
      size="small"
      (click)="switchSize('large')"
    />
  </syn-tooltip>
</syn-button-group>

// packages/_private/react-demo/src/SizeSwitch.tsx
import { useState } from 'react';
import {
  SynButtonGroup,
  SynIconButton,
  SynTooltip,
} from '@synergy-design-system/react';
import {
  type AllowedSizes,
  setGlobalSize,
} from '@synergy-design-system/demo-utilities';

export const SizeSwitch = () => {
  const [size, setSize] = useState<AllowedSizes>('medium');

  const handleSizeChange = (newSize: AllowedSizes) => {
    setSize(newSize);
    setGlobalSize(newSize);
  };

  return (
    <SynButtonGroup>
      <SynTooltip content="Set element size to small">
        <SynIconButton
          color={size === 'small' ? 'primary' : 'currentColor'}
          data-size="small"
          name="density_small"
          label="Set element size to small"
          size="small"
          onClick={() => handleSizeChange('small')}
        />
      </SynTooltip>
      <SynTooltip content="Set element size to medium">
        <SynIconButton
          color={size === 'medium' ? 'primary' : 'currentColor'}
          data-size="medium"
          name="density_medium"
          label="Set element size to medium"
          size="small"
          onClick={() => handleSizeChange('medium')}
        />
      </SynTooltip>
      <SynTooltip content="Set element size to large">
        <SynIconButton
          color={size === 'large' ? 'primary' : 'currentColor'}
          data-size="large"
          name="density_large"
          label="Set element size to large"
          size="small"
          onClick={() => handleSizeChange('large')}
        />
      </SynTooltip>
    </SynButtonGroup>
  );
};
