// packages/_private/vue-demo/src/SizeSwitch.vue
<script setup lang="ts">
import { ref } from 'vue';
import {
  SynVueButtonGroup,
  SynVueIconButton,
  SynVueTooltip,
} from '@synergy-design-system/vue';
import {
  type AllowedSizes,
  setGlobalSize,
} from '@synergy-design-system/demo-utilities';

const size = ref<AllowedSizes>('medium');

const handleSizeChange = (newSize: AllowedSizes) => {
  size.value = newSize;
  setGlobalSize(newSize);
};
</script>

<template>
  <SynVueButtonGroup>
    <SynVueTooltip content="Set element size to small">
      <SynVueIconButton
        :color="size === 'small' ? 'primary' : 'currentColor'"
        data-size="small"
        name="density_small"
        label="Set element size to small"
        size="small"
        @click="() => handleSizeChange('small')"
      />
    </SynVueTooltip>
    <SynVueTooltip content="Set element size to medium">
      <SynVueIconButton
        :color="size === 'medium' ? 'primary' : 'currentColor'"
        data-size="medium"
        name="density_medium"
        label="Set element size to medium"
        size="small"
        @click="() => handleSizeChange('medium')"
      />
    </SynVueTooltip>
    <SynVueTooltip content="Set element size to large">
      <SynVueIconButton
        :color="size === 'large' ? 'primary' : 'currentColor'"
        data-size="large"
        name="density_large"
        label="Set element size to large"
        size="small"
        @click="() => handleSizeChange('large')"
      />
    </SynVueTooltip>
  </SynVueButtonGroup>
</template>

// packages/_private/react-demo/src/SizeSwitch.tsx
import { useState } from 'react';
import {
  SynButtonGroup,
  SynIconButton,
  SynTooltip,
} from '@synergy-design-system/react';
import {
  type AllowedSizes,
  setGlobalSize,
} from '@synergy-design-system/demo-utilities';

export const SizeSwitch = () => {
  const [size, setSize] = useState<AllowedSizes>('medium');

  const handleSizeChange = (newSize: AllowedSizes) => {
    setSize(newSize);
    setGlobalSize(newSize);
  };

  return (
    <SynButtonGroup>
      <SynTooltip content="Set element size to small">
        <SynIconButton
          color={size === 'small' ? 'primary' : 'currentColor'}
          data-size="small"
          name="density_small"
          label="Set element size to small"
          size="small"
          onClick={() => handleSizeChange('small')}
        />
      </SynTooltip>
      <SynTooltip content="Set element size to medium">
        <SynIconButton
          color={size === 'medium' ? 'primary' : 'currentColor'}
          data-size="medium"
          name="density_medium"
          label="Set element size to medium"
          size="small"
          onClick={() => handleSizeChange('medium')}
        />
      </SynTooltip>
      <SynTooltip content="Set element size to large">
        <SynIconButton
          color={size === 'large' ? 'primary' : 'currentColor'}
          data-size="large"
          name="density_large"
          label="Set element size to large"
          size="small"
          onClick={() => handleSizeChange('large')}
        />
      </SynTooltip>
    </SynButtonGroup>
  );
};
