// packages/_private/angular-demo/src/themeswitch/themeswitch.component.ts
import { Component } from '@angular/core';
import type {
  SynChangeEvent,
  SynSwitch as SynSwitchElement,
} from '@synergy-design-system/components';

@Component({
  selector: 'theme-switch',
  templateUrl: './themeswitch.component.html',
})
export class ThemeSwitchComponent {

  currentTheme: string = '🌙';

  switchTheme(e: SynChangeEvent) {
    const { body } = document;
    const { checked } = e.target as SynSwitchElement;
    const theme = checked ? 'dark' : 'light';
    body.classList.remove('syn-theme-light', 'syn-theme-dark');
    body.classList.add(`syn-theme-${theme}`);

    this.currentTheme = theme === 'light' ? '🌙' : '☀️';
  }
}

<syn-switch (synChangeEvent)="switchTheme($event)">
  {{ currentTheme }}
</syn-switch>

// packages/_private/react-demo/src/ThemeSwitch.tsx
import { useState } from 'react';
import {
  type SynChangeEvent,
  SynSwitch,
} from '@synergy-design-system/react';
import type { SynSwitch as SynSwitchElement } from '@synergy-design-system/components';

export const ThemeSwitch = () => {
  const [currentTheme, setCurrentTheme] = useState('🌙');
  return (
    <SynSwitch
      onSynChange={(e: SynChangeEvent) => {
        const { body } = document;
        const { checked } = e.target as SynSwitchElement;
        const theme = checked ? 'dark' : 'light';
        body.classList.remove('syn-theme-light', 'syn-theme-dark');
        body.classList.add(`syn-theme-${theme}`);

        setCurrentTheme(theme === 'light' ? '🌙' : '☀️');
      }}
    >
      {currentTheme}
    </SynSwitch>
  );
};
