// packages/_private/angular-demo/src/AllComponentParts/Dropdown.ts
import { Component } from '@angular/core';
import { SynDropdownComponent, SynButtonComponent, SynMenuComponent, SynMenuItemComponent, SynDividerComponent, SynIconComponent } from '@synergy-design-system/angular';

@Component({
  selector: 'demo-dropdown',
  standalone: true,
  imports: [
    SynDropdownComponent,
    SynButtonComponent,
    SynMenuComponent,
    SynMenuItemComponent,
    SynDividerComponent,
    SynIconComponent,
  ],
  template: `
    <div style="position: relative;">
      <syn-dropdown>
        <syn-button slot="trigger" caret>Dropdown</syn-button>
        <syn-menu style="min-width: 240px;">
          <syn-menu-item>Dropdown Item 1</syn-menu-item>
          <syn-menu-item>Dropdown Item 2</syn-menu-item>
          <syn-menu-item>Dropdown Item 3</syn-menu-item>
          <syn-divider />
          <syn-menu-item type="checkbox" checked>Checkbox</syn-menu-item>
          <syn-menu-item disabled>Disabled</syn-menu-item>
          <syn-divider />
          <syn-menu-item>
            Prefix
            <syn-icon slot="prefix" name="wallpaper" />
          </syn-menu-item>
          <syn-menu-item>
            Suffix Icon
            <syn-icon slot="suffix" name="wallpaper" />
          </syn-menu-item>
        </syn-menu>
      </syn-dropdown>
    </div>
  `,
})
export class Dropdown {}

// packages/_private/react-demo/src/AllComponentParts/Dropdown.tsx
export const Dropdown = () => (
  <div style={{ position: 'relative' }}>
    <syn-dropdown>
      <syn-button slot="trigger" caret>Dropdown</syn-button>
      <syn-menu style={{ minWidth: 240 }}>
        <syn-menu-item>Dropdown Item 1</syn-menu-item>
        <syn-menu-item>Dropdown Item 2</syn-menu-item>
        <syn-menu-item>Dropdown Item 3</syn-menu-item>
        <syn-divider />
        <syn-menu-item type="checkbox" checked>Checkbox</syn-menu-item>
        <syn-menu-item disabled>Disabled</syn-menu-item>
        <syn-divider />
        <syn-menu-item>
          Prefix
          <syn-icon slot="prefix" name="wallpaper" />
        </syn-menu-item>
        <syn-menu-item>
          Suffix Icon
          <syn-icon slot="suffix" name="wallpaper" />
        </syn-menu-item>
      </syn-menu>
    </syn-dropdown>
  </div>
);
