// packages/_private/angular-demo/src/AllComponentParts/Validate.ts
import { Component, ViewChild } from '@angular/core';
import { SynInputComponent } from '@synergy-design-system/angular/components/input';
import { SynValidateComponent } from '@synergy-design-system/angular/components/validate';

@Component({
  selector: 'demo-validate',
  standalone: true,
  imports: [
    SynValidateComponent,
    SynInputComponent,
  ],
  template: `
    <syn-validate eager variant="inline" on="live">
      <syn-input
        label="Invalid input"
        type="email"
        value=""
        required
      />
    </syn-validate>

    <syn-validate #validate915 data-testid="validate-915" on="revalidate" variant="inline">
      <syn-input #input915 label="Incorrect state with custom event #915" (synChangeEvent)="setError('Invalid value')"/>
    </syn-validate>
  `,
})
export class Validate {
  @ViewChild('input915') input!: SynInputComponent;
  @ViewChild('validate915') validate!: SynValidateComponent;

  setError(message: string) {
    this.validate.customValidationMessage = message;
    this.input.nativeElement.dispatchEvent(new CustomEvent('revalidate', { bubbles: true}));
  }
}

// packages/_private/react-demo/src/AllComponentParts/Validate.tsx
import type { SynInput } from '@synergy-design-system/components';
import { useLayoutEffect, useRef, useState } from 'react';

export const Validate = () => {
  const [errorMsg, setError] = useState<string>('');
  const inputRef = useRef<SynInput>(null);
  useLayoutEffect(() => {
    inputRef.current?.dispatchEvent(new CustomEvent('revalidate'));
  }, [errorMsg]);

  return (
    <>
      <syn-validate eager variant="inline" on="live">
        <syn-input
          label="Invalid input"
          type="email"
          value=""
          required
        />
      </syn-validate>

      <syn-validate data-testid="validate-915" on="revalidate" customValidationMessage={errorMsg} variant="inline">
        <syn-input label="Incorrect state with custom event #915" ref={inputRef} onsyn-change={() => setError('Invalid value')} />
      </syn-validate>
    </>
  );
};
