// packages/_private/react-demo/src/AllComponentParts/Combobox.tsx
import { useEffect, useState } from 'react';
import type { SynCombobox } from '@synergy-design-system/components';
import {
  type SelectItem,
  mockAsyncData,
  mockData,
  updateComboboxRegressions1265,
} from '@synergy-design-system/demo-utilities';

const delimiterItems = mockData('selectItemsWithSpace');
const numericItems = mockData('selectItemsMixedValue');

export const Combobox = () => {
  const [levels, setLevels] = useState<SelectItem[]>([]);
  const [cb632Value, setcb632Value] = useState<string>('');
  const [asyncValue, setAsyncValue] = useState<string>('');

  const fetchLevels = async () => {
    const items = await mockAsyncData('selectItems');
    setLevels(items);
  };
  const fetchAsyncValue = async () => {
    const value = await mockAsyncData('valueWithSpace');
    setAsyncValue(value);
  };

  useEffect(() => {
    const bootstrap = async () => {
      await Promise.all([fetchLevels(), fetchAsyncValue()]);
    };
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    bootstrap();
  }, []);
  return (
    <>
      <syn-combobox data-testid="combobox-797" value="option-2">
        <syn-option value="option-1">Option 1</syn-option>
        <syn-option value="option-2">Option 2</syn-option>
        <syn-option value="option-3">Option 3</syn-option>
      </syn-combobox>

      <syn-combobox data-testid="combobox-level-813" label="Experience" help-text="Please tell us your skill level." value="2">
        {levels.map((level) => (
          <syn-option key={level.value} value={level.value}>
            {level.label}
          </syn-option>
        ))}
      </syn-combobox>

      <form>
        <syn-combobox data-testid="combobox-form-813" value="option-1">
          <syn-option value="option-1">Option 1</syn-option>
          <syn-option value="option-2">Option 2</syn-option>
          <syn-option value="option-3">Option 3</syn-option>
        </syn-combobox>
        <syn-button type="reset">Reset</syn-button>
      </form>

      <syn-combobox
        data-testid="combobox-632"
        label="Keyboard Interaction test #632"
        value={cb632Value}
        onsyn-change={(e) => setcb632Value((e.target as SynCombobox).value.toString())}
      >
        <syn-option value="option-1">Lorem</syn-option>
        <syn-option value="option-2">ipsum</syn-option>
        <syn-option value="option-3">dolor</syn-option>
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-626"
        label="'Restricted' feature #626"
        restricted
      >
        <syn-option value="option-1">Lorem</syn-option>
        <syn-option value="option-2">ipsum</syn-option>
        <syn-option value="option-3">dolor</syn-option>
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-626-async"
        label="'Restricted' feature #626 async"
        restricted
        value="3"
      >
        {levels.map(level => (
          <syn-option key={level.value} value={level.value}>
            {level.label}
          </syn-option>
        ))}
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-847-multiple"
        help-text="Normal value binding and async options"
        label="Multiple with async options"
        multiple
        value="1 2"
      >
        {levels.map(level => (
          <syn-option key={level.value} value={level.value}>
            {level.label}
          </syn-option>
        ))}
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-1036-subsequently-changed-delimiter"
        label="Subsequently changed delimiter"
      >
        {delimiterItems.map(item => (
          <syn-option key={item.value} value={item.value}>
            {item.label}
          </syn-option>
        ))}
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-1056-async-delimiter-change-with-pre-value"
        value="Option 2"
        label="Async changed delimiter with pre value"
        restricted
      >
        {delimiterItems.map(item => (
          <syn-option key={item.value} value={item.value}>
            {item.label}
          </syn-option>
        ))}
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-1056-async-delimiter-change-with-async-pre-value"
        value={asyncValue}
        label="Async changed delimiter with async pre value"
        restricted
      >
        {delimiterItems.map(item => (
          <syn-option key={item.value} value={item.value}>
            {item.label}
          </syn-option>
        ))}
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-627-delimiter"
        delimiter="+"
        help-text="This combobox uses a custom delimiter"
        label="Multiple with custom delimiter"
        multiple
        value="1+2"
      >
        {levels.map(level => (
          <syn-option key={level.value} value={level.value}>
            {level.label}
          </syn-option>
        ))}
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-805-single"
        help-text="Please tell us your skill level."
        label="Mixed integer and string values (Single Combobox)"
        value={1}
      >
        {numericItems.map(item => (
          <syn-option key={item.value} value={item.value} disabled={item.disabled}>
            {item.label}
          </syn-option>
        ))}
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-805-multi"
        help-text="Please tell us your skill level."
        label="Mixed integer and string values (multi Combobox)"
        multiple
        value={[1, 'three']}
      >
        {numericItems.map(item => (
          <syn-option key={item.value} value={item.value} disabled={item.disabled}>
            {item.label}
          </syn-option>
        ))}
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-885-value-zero-string"
        label="Combobox should allow to select value of string(zero)"
        value="0"
      >
        <syn-option value="0">Zero (string)</syn-option>
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-885-value-zero-number"
        label="Combobox should allow to select value of number(zero)"
        value={0}
      >
        <syn-option value={0}>Zero (numeric)</syn-option>
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-1172-readonly-combobox"
        label="Readonly Combobox"
        readonly
        value="option-1"
      >
        <syn-option value="option-1">Option 1</syn-option>
        <syn-option value="option-2">Option 2</syn-option>
        <syn-option value="option-3">Option 3</syn-option>
      </syn-combobox>

      <syn-combobox
        data-testid="combobox-1265-dynamic-option-changes"
        label="Dynamic Option Changes"
        restricted
        value="option-2"
      >
        <syn-option value="option-1">Option 1</syn-option>
        <syn-option value="option-2">Option 2</syn-option>
        <syn-option value="option-3">Option 2</syn-option>
      </syn-combobox>

      <syn-button
        data-testid="combobox-1265-dynamic-option-button"
        onClick={updateComboboxRegressions1265}
      >
        Dynamically change option 2 to "Changed Option 2"
      </syn-button>

    </>
  );
};

// packages/_private/angular-demo/src/AllComponentParts/Combobox.ts
import { Component, OnInit } from '@angular/core';
import type { SynChangeEvent, SynCombobox } from '@synergy-design-system/components';
import { SynComboboxComponent } from '@synergy-design-system/angular/components/combobox';
import { SynOptionComponent } from '@synergy-design-system/angular/components/option';
import { SynButtonComponent } from '@synergy-design-system/angular/components/button';
import {
  type SelectItem,
  mockAsyncData,
  mockData,
  updateComboboxRegressions1265 as updateComboboxRegressions1265Utility,
} from '@synergy-design-system/demo-utilities';

@Component({
  selector: 'demo-combobox',
  standalone: true,
  imports: [
    SynComboboxComponent,
    SynOptionComponent,
    SynButtonComponent
  ],
  template: `
    <syn-combobox data-testid="combobox-797" value="option-2">
      <syn-option value="option-1">Option 1</syn-option>
      <syn-option value="option-2">Option 2</syn-option>
      <syn-option value="option-3">Option 3</syn-option>
    </syn-combobox>

    <syn-combobox data-testid="combobox-level-813" label="Experience" help-text="Please tell us your skill level." [value]="'2'">
      @for (level of levels; track $index; let index = $index) {
        <syn-option [value]="level.value"> {{level.label}}</syn-option
        >
      }
    </syn-combobox>

    <form>
      <syn-combobox data-testid="combobox-form-813" [value]="'option-1'">
        <syn-option value="option-1">Option 1</syn-option>
        <syn-option value="option-2">Option 2</syn-option>
        <syn-option value="option-3">Option 3</syn-option>
      </syn-combobox>
      <syn-button type="reset">Reset</syn-button>
    </form>

    <syn-combobox
      data-testid="combobox-632"
      label="Keyboard Interaction test #632"
      [value]="cb632Value"
      (synChangeEvent)="setcb632Value($event)"
    >
      <syn-option value="option-1">Lorem</syn-option>
      <syn-option value="option-2">ipsum</syn-option>
      <syn-option value="option-3">dolor</syn-option>
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-626"
      label="'Restricted' feature #626"
      restricted
    >
      <syn-option value="option-1">Lorem</syn-option>
      <syn-option value="option-2">ipsum</syn-option>
      <syn-option value="option-3">dolor</syn-option>
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-626-async"
      label="'Restricted' feature #626 async"
      restricted
      value="3"
    >
      @for (level of levels; track $index; let index = $index) {
        <syn-option [value]="level.value">{{level.label}}</syn-option>
      }
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-847-multiple"
      help-text="Normal value binding and async options"
      label="Multiple with async options"
      multiple
      value="1 2"
    >
      @for (level of levels; track $index; let index = $index) {
        <syn-option [value]="level.value">{{level.label}}</syn-option>
      }
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-1036-subsequently-changed-delimiter"
      label="Subsequently changed delimiter"
    >
      @for (item of delimiterItems; track $index; let index = $index) {
        <syn-option [value]="item.value">{{item.label}}</syn-option>
      }
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-1056-async-delimiter-change-with-pre-value"
      value="Option 2"
      label="Async changed delimiter with pre value"
      restricted
    >
      @for (item of delimiterItems; track $index; let index = $index) {
        <syn-option [value]="item.value">{{item.label}}</syn-option>
      }
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-1056-async-delimiter-change-with-async-pre-value"
      [value]="asyncValue"
      label="Async changed delimiter with async pre value"
      restricted
    >
      @for (item of delimiterItems; track $index; let index = $index) {
        <syn-option [value]="item.value">{{item.label}}</syn-option>
      }
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-627-delimiter"
      delimiter="+"
      help-text="This combobox uses a custom delimiter"
      label="Multiple with custom delimiter"
      multiple
      value="1+2"
    >
      @for (level of levels; track $index; let index = $index) {
        <syn-option [value]="level.value">{{level.label}}</syn-option>
      }
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-805-single"
      help-text="Please tell us your skill level."
      label="Mixed integer and string values (Single Combobox)"
      [value]=1
    >
      @for (item of numericItems; track $index; let index = $index) {
        <syn-option [value]="item.value"> {{item.label}}</syn-option>
      }
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-805-multi"
      help-text="Please tell us your skill level."
      label="Mixed integer and string values (multi Combobox)"
      multiple
      [value]="[1, 'three']"
    >
      @for (item of numericItems; track $index; let index = $index) {
        <syn-option [value]="item.value"> {{item.label}}</syn-option>
      }
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-885-value-zero-string"
      label="Combobox should allow to select value of string(zero)"
      value="0"
    >
      <syn-option value="0">Zero (string)</syn-option>
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-885-value-zero-number"
      label="Combobox should allow to select value of number(zero)"
      [value]=0
    >
      <syn-option [value]=0>Zero (numeric)</syn-option>
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-1172-readonly-combobox"
      label="Readonly Combobox"
      readonly
      value="option-1"
    >
      <syn-option value="option-1">Option 1</syn-option>
      <syn-option value="option-2">Option 2</syn-option>
      <syn-option value="option-3">Option 3</syn-option>
    </syn-combobox>

    <syn-combobox
      data-testid="combobox-1265-dynamic-option-changes"
      label="Dynamic Option Changes"
      restricted
      value="option-2"
    >
      <syn-option value="option-1">Option 1</syn-option>
      <syn-option value="option-2">Option 2</syn-option>
      <syn-option value="option-3">Option 2</syn-option>
    </syn-combobox>

    <syn-button data-testid="combobox-1265-dynamic-option-button" (click)="updateComboboxRegressions1265($event)">
      Dynamically change option 2 to "Changed Option 2"
    </syn-button>
  `,
})
export class Combobox implements OnInit {
  levels: SelectItem[] = mockData('selectItems');
  delimiterItems = mockData('selectItemsWithSpace');
  numericItems = mockData('selectItemsMixedValue');
  cb632Value: string = '';
  asyncValue: string = mockData('valueWithSpace');

  setcb632Value(e: SynChangeEvent) {
    this.cb632Value = (e.target as SynCombobox).value as string;
  };

  updateComboboxRegressions1265(e: Event): void {
    updateComboboxRegressions1265Utility(e);
  }

  ngOnInit(): void {
    mockAsyncData('selectItems').then((items) => {
      this.levels = items;
    });
    mockAsyncData('valueWithSpace').then((value) => {
      this.asyncValue = value;
    });
  }
}
