// packages/_private/react-demo/src/AllComponentParts/LineChart.tsx
import '@synergy-design-system/components/components/chart/chart.js';
import type { ChartConfigCallback } from '@synergy-design-system/components/components/chart/types.js';
import { mockData } from '@synergy-design-system/demo-utilities';

const lineChartConfig: ChartConfigCallback = (handle) => {
  handle.baseConfig(mockData('generalChartConfig'))
    .seriesLine(mockData('lineChartSeriesData'))
    .legendShow();
};

export const LineChart = () => (
  <syn-chart config={lineChartConfig} />
);

// packages/_private/angular-demo/src/AllComponentParts/LineChart.ts
import { Component } from '@angular/core';
import { SynChartComponent } from '@synergy-design-system/angular/components/chart';
import type { ChartConfigCallback } from '@synergy-design-system/components/components/chart/types.js';
import { mockData } from '@synergy-design-system/demo-utilities';

@Component({
  selector: 'demo-line-chart',
  standalone: true,
  imports: [
    SynChartComponent,
  ],
  template: `
    <syn-chart [config]="lineChartConfig"></syn-chart>
  `,
})
export class LineChart {
  lineChartConfig: ChartConfigCallback = (handle) => {
    handle
    .baseConfig(mockData('generalChartConfig'))
    .seriesLine(mockData('lineChartSeriesData'))
    .legendShow();
  };
}
