// packages/_private/angular-demo/src/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: false,
  styleUrls: ['./app.component.css'],
  templateUrl: './app.component.html',
})
export class AppComponent {
}

<syn-header label="synergy-design-system/angular Components Demo">
  <a
    aria-label="Back to homepage"
    class="custom-logo"
    href="/"
    routerLink="/"
    slot="logo"
    tabindex="0"
  >
    <syn-icon name="logo-color" library="system" />
  </a>
  <span>Turbosnap test</span>
  <div class="meta-navigation" slot="meta-navigation">
    <sidenav-switch />
    <syn-divider vertical />
    <size-switch />
    <syn-divider vertical />
    <theme-switch />
  </div>
</syn-header>

<div class="main">
  <syn-side-nav variant="rail">
    <syn-nav-item routerLink="/" routerLinkActive [routerLinkActiveOptions]="{exact: true}">
      Home
      <syn-icon name="home" slot="prefix"></syn-icon>
    </syn-nav-item>
    <syn-nav-item divider routerLink="/contact-form" routerLinkActive [routerLinkActiveOptions]="{exact: true}">
      Contact Form
      <syn-icon name="contact_mail" slot="prefix"></syn-icon>
    </syn-nav-item>
    <syn-nav-item divider routerLink="/contact-form-validate" routerLinkActive [routerLinkActiveOptions]="{exact: true}">
      Contact Form (Validation)
      <syn-icon name="contact_emergency" slot="prefix"></syn-icon>
    </syn-nav-item>
    <syn-nav-item divider routerLink="/all-components" routerLinkActive [routerLinkActiveOptions]="{exact: true}">
      All Components
      <syn-icon name="grid_view" slot="prefix"></syn-icon>
    </syn-nav-item>
    <syn-nav-item divider routerLink="/framework-specific" routerLinkActive [routerLinkActiveOptions]="{exact: true}">
      Framework specific issues
      <syn-icon name="bug_report" slot="prefix"></syn-icon>
    </syn-nav-item>
  </syn-side-nav>
  <main class="content">
    <router-outlet></router-outlet>
  </main>
</div>

// packages/_private/vue-demo/src/App.vue
<script setup lang="ts">
import SizeSwitch from './SizeSwitch.vue';
import ThemeSwitch from './ThemeSwitch.vue';
import { SynVueDivider, SynVueHeader, SynVueIcon, SynVueNavItem, SynVueSideNav } from '@synergy-design-system/vue';
import { computed } from 'vue';
import { RouterLink, useRouter } from 'vue-router';

const router = useRouter();

const currentRoute = computed(() => router.currentRoute.value.path);

const routeTo = (route: string) => {
  router.push(route);
}
</script>

<template>
  <SynVueHeader label="@synergy-design-system/vue Components Demo">
    <RouterLink aria-label="Back to homepage" class="custom-logo" tabindex="0" to="/" slot="logo">
      <SynVueIcon name="logo-color" library="system" />
    </RouterLink>
    <div class="meta-navigation" slot="meta-navigation">
      <SizeSwitch />
      <SynVueDivider vertical />
      <ThemeSwitch />
    </div>
  </SynVueHeader>

  <div class="main">
    <SynVueSideNav variant="rail" ref="sideNavRef">
      <SynVueNavItem :current="currentRoute === '/'" @click="() => routeTo('/')">
        Home
        <SynVueIcon name="home" slot="prefix"/>
      </SynVueNavItem>
      <SynVueNavItem :current="currentRoute === '/contact-form'" divider @click="() => routeTo('/contact-form')">
        Contact Form
        <SynVueIcon name="contact_mail" slot="prefix"/>
      </SynVueNavItem>
      <SynVueNavItem :current="currentRoute === '/contact-form-validate'" divider @click="() => routeTo('/contact-form-validate')">
        Contact Form (Validation)
        <SynVueIcon name="contact_emergency" slot="prefix"/>
      </SynVueNavItem>
      <SynVueNavItem :current="currentRoute === '/all-components'" divider @click="() => routeTo('/all-components')">
        All Components
        <SynVueIcon name="grid_view" slot="prefix"/>
      </SynVueNavItem>
    </SynVueSideNav>
    <main class="content">
      <RouterView />
    </main>
  </div>
</template>

<style scoped>
syn-header {
  position: sticky;
  top: 0;
  z-index: 50;
}

.custom-logo syn-icon {
  display: block;
  width: auto;
  height: 32px;
}

.meta-navigation {
  align-items: center;
  display: flex;
}

/* Safari fix for ##623 */
.custom-logo syn-icon::part(svg) {
  width: auto;
}

.main {
  flex-grow: 1;
  display: flex;
  position: relative;
  background: var(--syn-color-neutral-0);
  overflow: hidden;
}

.content {
  box-sizing: border-box;
  flex-grow: 1;
  padding: var(--syn-spacing-medium) var(--syn-spacing-large);
  height: 100%;
  overflow-y: auto;
}
</style>
