// packages/_private/react-demo/src/DemoForm.tsx
/* eslint-disable no-console */
import { useEffect, useRef, useState } from 'react';
import { serialize } from '@synergy-design-system/components';
import type {
  SynCheckbox as NativeCheckbox,
  SynFile as NativeFile,
  SynChangeEvent,
  SynRange as SynRangeNativeElement,
} from '@synergy-design-system/components';
import {
  SynButton,
  SynCheckbox,
  SynDivider,
  SynFile,
  SynInput,
  SynOptgroup,
  SynOption,
  SynRadio,
  SynRadioGroup,
  SynRange,
  SynRangeTick,
  SynSelect,
  SynSwitch,
  SynTextarea,
  SynValidate,
} from '@synergy-design-system/react';
import { DemoFieldset } from './DemoFieldset';

type FormEnabledElements = HTMLElement & {
  checked?: boolean;
  name: string;
  value?: string;
};

const initialFormData = {
  code: '',
  comment: '',
  date: '',
  donations: '2000 4000',
  email: '',
  files: undefined,
  gender: '',
  happiness: '5',
  name: '',
  newsletterAngular: false,
  newsletterBeta: false,
  newsletterReact: false,
  newsletterStandard: false,
  newsletterVanilla: false,
  newsletterVue: false,
  password: 'invalid',
  phone: '',
  role: '',
  topics: [],
};

const formatter = new Intl.NumberFormat('de-DE', {
  currency: 'EUR',
  maximumFractionDigits: 0,
  style: 'currency',
});

export const DemoForm = () => {
  const donationsRef = useRef<SynRangeNativeElement>(null);
  const formRef = useRef<HTMLFormElement>(null);
  const [formData, setFormData] = useState(initialFormData);

  // This is needed, as shoelace does its event with `syn-` prefix
  // and react wont let us bind arbitary custom events :(
  useEffect(() => {
    // Add a custom formatter for the donation field
    donationsRef.current!.tooltipFormatter = value => formatter.format(value);

    const listener = (e: SynChangeEvent) => {
      const form = formRef.current as HTMLFormElement;

      const normalizedData = serialize(form);

      // Log the normalized data
      console.log(normalizedData);

      // Set the field into state
      const element = e.target as FormEnabledElements;
      const { name, value } = element;

      let finalValue;

      switch (element.tagName.toLocaleLowerCase()) {
      case 'syn-checkbox':
      case 'syn-switch':
        finalValue = (element as NativeCheckbox).checked;
        break;
      case 'syn-file': finalValue = (element as NativeFile).files; break;
      default: finalValue = value;
      }

      setFormData((curr) => ({
        ...curr,
        [name]: finalValue,
      }));
    };

    formRef.current?.addEventListener('syn-change', listener);
    return () => {
      formRef.current?.removeEventListener('syn-change', listener);
    };
  }, []);

  return (
    <form
      encType="multipart/form-data"
      method="post"
      onReset={() => {
        setFormData(initialFormData);
      }}
      onSubmit={e => {
        e.preventDefault();
        e.stopPropagation();

        const formElement = e.target as HTMLFormElement;
        const isValid = formElement.checkValidity();

        const content = isValid
          ? 'Your data was successfully submitted'
          : 'Your data could not be submitted! Please provide all required information!';

        // eslint-disable-next-line no-alert
        alert(content);
      }}
      ref={formRef}
    >

      {/* PersonalInformation */}
      <DemoFieldset legend="Personal Information">

        <SynValidate inline>
          <SynRadioGroup
            id="radiogroup-gender"
            name="gender"
            label="Please tell us your gender"
            required
            value={formData.gender}
          >
            <SynRadio value="f">Female</SynRadio>
            <SynRadio value="m">Male</SynRadio>
            <SynRadio value="other">Other</SynRadio>
          </SynRadioGroup>
        </SynValidate>

        <SynValidate inline>
          <SynSelect
            id="select-role"
            label="Current position"
            name="role"
            required
            value={formData.role}
          >
            <SynOptgroup label="Developers">
              <SynOption value="backend">Backend Developer</SynOption>
              <SynOption value="frontend">Frontend Developer</SynOption>
            </SynOptgroup>
            <SynOptgroup label="Other">
              <SynOption value="lead">Team Lead</SynOption>
              <SynOption value="other">Other (please specify in comment section below)</SynOption>
            </SynOptgroup>
          </SynSelect>
        </SynValidate>

        <SynInput
          id="input-text"
          label="Name"
          minlength={5}
          maxlength={20}
          name="name"
          placeholder="Please insert a value for the regular text input (between 5 and 20 Characters)"
          required
          value={formData.name}
          type="text"
        />

        <SynInput
          id="input-email"
          label="E-Mail"
          name="email"
          placeholder="Please insert your E-mail address"
          required
          value={formData.email}
          type="email"
        />

        <SynInput
          id="input-phone"
          label="Phone"
          name="phone"
          placeholder="Please provide your phone number"
          required
          value={formData.phone}
          type="tel"
        />

        <SynInput
          id="input-date"
          label="Date of birth"
          name="date"
          value={formData.date}
          type="date"
        />

      </DemoFieldset>
      {/* /PersonalInformation */}

      <SynDivider />

      {/* Security */}
      <DemoFieldset legend="Security">
        <SynValidate inline>
          <SynInput
            id="input-password"
            label="Provide a secure password"
            name="password"
            password-toggle
            pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
            placeholder="Please provide at least one uppercase and lowercase letter and a number"
            required
            type="password"
            value={formData.password}
          />
        </SynValidate>

        <SynInput
          id="input-number"
          label="Please provide a fallback numeric value that may be used for password recovery"
          min="1000"
          max="9999"
          name="code"
          placeholder="Please choose a value with four digits, e.g. 1234"
          type="number"
          value={formData.code}
        />
      </DemoFieldset>
      {/* /Security */}

      <SynDivider />

      {/* Topics */}
      <DemoFieldset legend="Topics">
        <SynSelect
          clearable
          id="topics"
          label="I am interested in the following technologies"
          multiple
          name="topics"
          value={formData.topics.join(' ')}
        >
          <SynOptgroup label="Frontend">
            <SynOption value="angular">Angular</SynOption>
            <SynOption value="react">React.js</SynOption>
            <SynOption value="vanilla">Vanilla.js</SynOption>
            <SynOption value="vue">Vue</SynOption>
          </SynOptgroup>
          <SynOptgroup label="Backend">
            <SynOption value="node">Node.js</SynOption>
            <SynOption value="Python">Python</SynOption>
          </SynOptgroup>
        </SynSelect>
      </DemoFieldset>
      {/* /Topics */}

      <SynDivider />

      {/* Happiness */}
      <DemoFieldset id="happiness-fields" legend="Happiness">
        <SynRange
          id="happiness"
          label="How happy are you with the Synergy Design System?"
          max={10}
          min={0}
          name="happiness"
          value={formData.happiness}
        >
          <nav slot="ticks">
            <SynRangeTick>🤮</SynRangeTick>
            <SynRangeTick>🥱</SynRangeTick>
            <SynRangeTick>😍</SynRangeTick>
          </nav>
        </SynRange>

        <SynRange
          id="donations"
          label="I would donate between"
          max={6000}
          min={0}
          name="donations"
          value={formData.donations}
          ref={donationsRef}
        >
          <nav slot="ticks">
            <SynRangeTick>0 €</SynRangeTick>
            <SynRangeTick>6.000 €</SynRangeTick>
          </nav>
        </SynRange>

      </DemoFieldset>
      {/* /Happiness */}

      <SynDivider />

      {/* Marketing */}
      <DemoFieldset legend="Please inform me about the following technologies">
        <SynCheckbox
          checked={formData.newsletterStandard}
          id="checkbox-newsletter-default"
          name="newsletterStandard"
        >
          Please subscribe me to the synergy newsletter
        </SynCheckbox>
        <SynCheckbox
          checked={formData.newsletterAngular}
          id="checkbox-newsletter-angular"
          name="newsletterAngular"
        >
          Please subscribe me to all things related to angular
        </SynCheckbox>
        <SynCheckbox
          checked={formData.newsletterReact}
          id="checkbox-newsletter-react"
          name="newsletterReact"
        >
          Please subscribe me to all things related to react
        </SynCheckbox>
        <SynCheckbox
          checked={formData.newsletterVanilla}
          id="checkbox-newsletter-vanilla"
          name="newsletterVanilla"
        >
          Please subscribe me to all things related to vanilla.js
        </SynCheckbox>
        <SynCheckbox
          checked={formData.newsletterVue}
          id="checkbox-newsletter-vue"
          name="newsletterVue"
        >
          Please subscribe me to all things related to vue
        </SynCheckbox>
        <SynSwitch
          checked={formData.newsletterBeta}
          id="checkbox-newsletter-beta"
          name="newsletterBeta"
        >
          I am interested in the Synergy Beta Program
        </SynSwitch>
      </DemoFieldset>
      {/* /Marketing */}

      <SynDivider />

      { /* AdditionalInformation */ }
      <DemoFieldset legend="Additional Information">
        <SynTextarea
          id="additional-info"
          label="Comment"
          name="comment"
          placeholder="Please provide additional information that might be helpful for your inquiry"
          rows={10}
        >
          {formData.comment}
        </SynTextarea>
        <SynFile
          accept="image/*"
          droparea
          help-text="Please upload images only"
          files={formData.files}
          id="screenshot"
          label="Optional Screenshot(s)"
          multiple
          name="files"
        />
      </DemoFieldset>

      { /* /AdditionalInformation */ }

      <SynDivider />

      {/* Actions */}
      <div className="syn-fieldset syn-submit-buttons">
        <SynButton variant="outline" type="reset">Reset</SynButton>
        <SynButton variant="filled" type="submit">Send</SynButton>
      </div>
      {/* /Actions */}

    </form>
  );
};

// packages/_private/vue-demo/src/DemoForm.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import {
  SynVueButton,
  SynVueCheckbox,
  SynVueDivider,
  SynVueFile,
  SynVueInput,
  SynVueOptgroup,
  SynVueOption,
  SynVueRadio,
  SynVueRange,
  SynVueRangeTick,
  SynVueRadioGroup,
  SynVueSelect,
  SynVueSwitch,
  SynVueTextarea,
} from '@synergy-design-system/vue';
import { serialize } from '@synergy-design-system/components';
import DemoFieldset from './DemoFieldset.vue';

const initialFormData = {
  code: '',
  comment: '',
  date: '',
  donations: '2000 4000',
  email: '',
  files: undefined,
  gender: '',
  happiness: '5',
  name: '',
  newsletterAngular: false,
  newsletterBeta: false,
  newsletterReact: false,
  newsletterStandard: false,
  newsletterVanilla: false,
  newsletterVue: false,
  password: 'invalid',
  phone: '',
  role: '',
  topics: [],
};

const formData = ref({
  ...initialFormData,
});

const formRef = ref<HTMLFormElement>();

// Custom formatter for donations
const donationsRef = ref<InstanceType<typeof SynVueRange> | null>(null);

onMounted(() => {
  const formatter = new Intl.NumberFormat('de-DE', {
    currency: 'EUR',
    maximumFractionDigits: 0,
    style: 'currency',
  });

  // Add a custom formatter for the donation field
  donationsRef.value!.nativeElement!.tooltipFormatter = value => formatter.format(value);
});

const reset = () => {
  formData.value = {
    ...initialFormData,
  };
}

const submit = (e: Event) => {
  e.preventDefault();
  e.stopPropagation();

  const formElement = e.target as HTMLFormElement;
  const isValid = formElement.checkValidity();

  if (isValid) {
    // eslint-disable-next-line no-alert
    alert('Your data was successfully submitted');
  }
}

const synChange = () => {
  const normalizedData = serialize(formRef.value!);

  // Log the normalized data
  console.log(normalizedData);
};
</script>

<template>
  <form
    @reset="reset"
    @submit="submit"
    @syn-change="synChange"
    ref="formRef"
  >
    <!-- PersonalInformation -->
    <DemoFieldset legend="Personal Information">

      <SynVueRadioGroup
        id="radiogroup-gender"
        name="gender"
        label="Please tell us your gender"
        required
        v-model="formData.gender"
      >
        <SynVueRadio value="f">Female</SynVueRadio>
        <SynVueRadio value="m">Male</SynVueRadio>
        <SynVueRadio value="other">Other</SynVueRadio>
      </SynVueRadioGroup>

      <SynVueSelect
        id="select-role"
        label="Current position"
        name="role"
        required
        v-model="formData.role"
      >
        <SynVueOptgroup label="Developers">
          <SynVueOption value="backend">Backend Developer</SynVueOption>
          <SynVueOption value="frontend">Frontend Developer</SynVueOption>
        </SynVueOptgroup>
        <SynVueOptgroup label="Other">
          <SynVueOption value="lead">Team Lead</SynVueOption>
          <SynVueOption value="other">Other (please specify in comment section below)</SynVueOption>
        </SynVueOptgroup>
      </SynVueSelect>

      <SynVueInput
        id="input-text"
        label="Name"
        :minlength="5"
        :maxlength="20"
        name="name"
        placeholder="Please insert a value for the regular text input (between 5 and 20 Characters)"
        required
        v-model="formData.name"
        type="text"
      />

      <SynVueInput
        id="input-email"
        label="E-Mail"
        name="email"
        placeholder="Please insert your E-mail address"
        required
        v-model="formData.email"
        type="email"
      />

      <SynVueInput
        id="input-phone"
        label="Phone"
        name="phone"
        placeholder="Please provide your phone number"
        required
        v-model="formData.phone"
        type="tel"
      />

      <SynVueInput
        id="input-date"
        label="Date of birth"
        name="date"
        placeholder="Please insert your E-mail address"
        v-model="formData.date"
        type="date"
      />

    </DemoFieldset>
    <!-- /PersonalInformation -->

    <SynVueDivider />

    <!-- Security -->
    <DemoFieldset legend="Security">
      <SynVueInput
        id="input-password"
        label="Provide a secure password"
        name="password"
        password-toggle
        pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
        placeholder="Please provide at least one uppercase and lowercase letter and a number"
        required
        type="password"
        v-model="formData.password"
      />

      <SynVueInput
        id="input-number"
        label="Please provide a fallback numeric value that may be used for password recovery"
        min="1000"
        max="9999"
        name="code"
        placeholder="Please choose a value with four digits, e.g. 1234"
        type="number"
        v-model="formData.code"
      />
    </DemoFieldset>
    <!-- /Security -->

    <SynVueDivider />

    <!-- Topics -->
    <DemoFieldset legend="Topics">
      <SynVueSelect
        clearable
        id="topics"
        label="I am interested in the following technologies"
        multiple
        name="topics"
        v-model="formData.topics"
      >
        <SynVueOptgroup label="Frontend">
          <SynVueOption value="angular">Angular</SynVueOption>
          <SynVueOption value="react">React.js</SynVueOption>
          <SynVueOption value="vanilla">Vanilla.js</SynVueOption>
          <SynVueOption value="vue">Vue</SynVueOption>
        </SynVueOptgroup>
        <SynVueOptgroup label="Backend">
          <SynVueOption value="node">Node.js</SynVueOption>
          <SynVueOption value="Python">Python</SynVueOption>
        </SynVueOptgroup>
      </SynVueSelect>
    </DemoFieldset>
    <!-- /Topics -->

    <SynVueDivider />

    <!-- Happiness -->
    <DemoFieldset id="happiness-fields" legend="Happiness">
      <SynVueRange
        id="happiness"
        label="How happy are you with the Synergy Design System?"
        :max="10"
        :min="0"
        name="happiness"
        v-model="formData.happiness"
      >
        <nav slot="ticks">
          <SynVueRangeTick label="🤮"></SynVueRangeTick>
          <SynVueRangeTick label="🥱"></SynVueRangeTick>
          <SynVueRangeTick label="😍"></SynVueRangeTick>
        </nav>
      </SynVueRange>

      <SynVueRange
        id="donations"
        label="I would donate between"
        :max="6000"
        :min="0"
        name="donations"
        v-model="formData.donations"
        ref="donationsRef"
      >
        <nav slot="ticks">
          <syn-range-tick>0 €</syn-range-tick>
          <syn-range-tick>6.000 €</syn-range-tick>
        </nav>
      </SynVueRange>
    </DemoFieldset>
    <!-- /.Happiness -->

    <SynVueDivider />

    <!-- Marketing -->
    <DemoFieldset legend="Please inform me about the following technologies">
      <SynVueCheckbox
        id="checkbox-newsletter-default"
        name="newsletterStandard"
        v-model="formData.newsletterStandard"
      >
        Please subscribe me to the synergy newsletter
      </SynVueCheckbox>
      <SynVueCheckbox
        id="checkbox-newsletter-angular"
        name="newsletterAngular"
        v-model="formData.newsletterAngular"
      >
        Please subscribe me to all things related to angular
      </SynVueCheckbox>
      <SynVueCheckbox
        id="checkbox-newsletter-react"
        name="newsletterReact"
        v-model="formData.newsletterReact"
      >
        Please subscribe me to all things related to react
      </SynVueCheckbox>
      <SynVueCheckbox
        id="checkbox-newsletter-vanilla"
        name="newsletterVanilla"
        v-model="formData.newsletterVanilla"
      >
        Please subscribe me to all things related to vanilla.js
      </SynVueCheckbox>
      <SynVueCheckbox
        id="checkbox-newsletter-vue"
        name="newsletterVue"
        v-model="formData.newsletterVue"
      >
        Please subscribe me to all things related to vue
      </SynVueCheckbox>
      <SynVueSwitch
        id="checkbox-newsletter-beta"
        name="newsletterBeta"
        v-model="formData.newsletterBeta"
      >
        I am interested in the Synergy Beta Program
      </SynVueSwitch>
    </DemoFieldset>
    <!-- /Marketing -->

    <SynVueDivider />

    <!-- AdditionalInformation -->
    <DemoFieldset legend="Additional Information">
      <SynVueTextarea
        id="additional-info"
        label="Comment"
        name="comment"
        placeholder="Please provide additional information that might be helpful for your inquiry"
        :rows="10"
        v-model="formData.comment"
      />
      <SynVueFile
        accept="image/*"
        droparea
        help-text="Please upload images only"
        id="screenshot"
        label="Optional Screenshot(s)"
        multiple
        name="files"
        v-model="formData.files"
      />
    </DemoFieldset>
    <!-- /AdditionalInformation -->

    <SynVueDivider />

    <!-- Actions -->
    <div class="syn-submit-buttons">
      <SynVueButton variant="outline" type="reset">Reset</SynVueButton>
      <SynVueButton variant="filled" type="submit">Send</SynVueButton>
    </div>
    <!-- /Actions -->

  </form>
</template>

<style scoped>
form syn-divider {
  --spacing: var(--syn-spacing-2x-large);
}

form .syn-fieldset:last-of-type {
  margin-bottom: 0;
}

.syn-legend {
  font-size: var(--syn-font-size-large);
  margin-bottom: var(--syn-spacing-medium);
}

.syn-submit-buttons {
  align-items: center;
  border: none;
  display: flex;
  flex-direction: row;
  gap: var(--syn-spacing-large);
  margin: 0 0 var(--syn-spacing-2x-large) 0;
  padding: 0;
  justify-content: center;
}

/* Special overrides */
#happiness-fields syn-range nav {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

#radiogroup-gender::part(form-control-input) {
  display: flex;
  gap: var(--syn-spacing-medium);
}
</style>
