// packages/_private/angular-demo/src/demos-template/demos-template.component.ts
import { Component } from '@angular/core';
import { SynTabGroupComponent, SynTabComponent, SynTabPanelComponent } from '@synergy-design-system/angular';
import { CommonModule, type NgComponentOutlet } from '@angular/common';
import { type SynTabShowEvent } from '@synergy-design-system/components';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'demos-template',
  standalone: true,
  imports: [
    CommonModule,
    SynTabGroupComponent,
    SynTabComponent,
    SynTabPanelComponent,
  ],
  templateUrl: './demos-template.component.html',
})
export class DemosTemplateComponent {
  activeDemo = '';

  demos: Array<[string, typeof NgComponentOutlet]> = [];


  constructor(private route: ActivatedRoute) {
    const routeDemos = this.route.snapshot.data['demos'];
    if (routeDemos) {
      this.demos = routeDemos;
    }
    this.activeDemo = this.demos[0]?.[0] || '';
  }

  handleTabShow = (e: SynTabShowEvent) => {
    const { name } = e.detail;
    (e.target as HTMLElement).parentElement?.scrollTo(0, 0);

    const dialog = document.querySelector('syn-dialog');
    if (dialog) {
      dialog.open = name === 'Dialog';
    }
  }
}

@if (demos.length === 0) {
  <span> There are no demos available.</span>
} @else {
  <syn-tab-group
    class="demo-tab-group"
    (syn-tab-show)="handleTabShow($event)"
    placement='end'
  >
    @for (demo of demos; track demo[0]) {
      <syn-tab
        [active]="demo[0] === activeDemo"
        [id]="'tab-' + demo[0]"
        [panel]="demo[0]"
        slot="nav"
      >
        {{demo[0]}}
      </syn-tab>
      <syn-tab-panel
        [active]="demo[0] === activeDemo"
        [name]="demo[0]"
      >
        @if (demo[0] === activeDemo) {
          <div [id]="'tab-content-' + demo[0]">
            <h1 class="syn-heading--3x-large">{{demo[0]}}</h1>
            <syn-divider></syn-divider>
            <ng-container *ngComponentOutlet="demo[1]"></ng-container>
          </div>
        }
      </syn-tab-panel>
    }
  </syn-tab-group>
}

// packages/_private/vue-demo/src/DemosTemplate.vue
<script setup lang="ts">
import { SynVueDivider, SynVueTab, SynVueTabGroup, SynVueTabPanel } from '@synergy-design-system/vue';
import type { SynTabShowEvent } from '@synergy-design-system/components';
import { type Component } from 'vue';

import { computed } from 'vue';
const props = defineProps<{ demos: [string, Component][] }>();
const demos = computed(() => props.demos);

const activeDemo = computed( () => demos.value[0]?.[0] || '');

const showTab = (e: SynTabShowEvent) => {
  const { name } = e.detail;
  (e.target as HTMLElement).parentElement?.scrollTo(0, 0);

  const dialog = document.querySelector('syn-dialog');
  if (dialog) {
    dialog.open = name === 'Dialog';
  }
};
</script>

<template>
  <span v-if="demos.length === 0">
    There are no demos available.
  </span>

  <SynVueTabGroup
    class="demo-tab-group"
    @syn-tab-show="showTab"
    placement="end"
    v-else
  >
    <template
      v-for="([name, Component]) in demos"
      :key="name"
    >
      <SynVueTab
        :active="name === activeDemo"
        :id="`tab-${name}`"
        :panel="name as string"
        slot="nav"
      >
        {{name}}
      </SynVueTab>
      <SynVueTabPanel
        :active="name === activeDemo"
        :name="name as string"
      >
        <div :id="`tab-content-${name}`" style="display: 'contents';">
          <h1 className="syn-heading--3x-large">{{name}}</h1>
          <SynVueDivider />
          <component :is="Component" />
        </div>
      </SynVueTabPanel>
    </template>
  </SynVueTabGroup>
</template>
