// packages/_private/react-demo/src/SidenavSwitch.tsx
import { useEffect, useState } from 'react';
import { type SideNavTypes } from '@synergy-design-system/demo-utilities';

export const SidenavSwitch = () => {
  const [type, setType] = useState<SideNavTypes>('rail');

  useEffect(() => {
    const sideNav = document.querySelector('syn-side-nav');
    if (sideNav) {
      sideNav.variant = type;
    }
  }, [type]);

  return (
    <syn-button-group>
      <syn-tooltip content="Set sidenav to default">
        <syn-icon-button
          color={type === 'default' ? 'primary' : 'currentColor'}
          data-type="default"
          label="Set navigation to default"
          name="lunch_dining"
          size="small"
          onClick={() => setType('default')}
        />
      </syn-tooltip>
      <syn-tooltip content="Set sidenav to rail">
        <syn-icon-button
          color={type === 'rail' ? 'primary' : 'currentColor'}
          data-type="rail"
          label="Set navigation to rail"
          name="space_dashboard"
          size="small"
          onClick={() => setType('rail')}
        />
      </syn-tooltip>
      <syn-tooltip content="Set sidenav to sticky">
        <syn-icon-button
          color={type === 'sticky' ? 'primary' : 'currentColor'}
          data-type="sticky"
          label="Set navigation to sticky"
          name="preview"
          size="small"
          onClick={() => setType('sticky')}
        />
      </syn-tooltip>
    </syn-button-group>
  );
};

// packages/_private/vue-demo/src/SidenavSwitch.vue
<script setup lang="ts">
import { ref } from 'vue';
import {
  SynVueButtonGroup,
  SynVueIconButton,
  SynVueTooltip,
} from '@synergy-design-system/vue';
import { type SideNavTypes } from '@synergy-design-system/demo-utilities';

const type = ref<SideNavTypes>('rail');

const setType = (newType: SideNavTypes) => {
  type.value = newType;
  const sideNav = document.querySelector('syn-side-nav');
  if (sideNav) {
    sideNav.variant = newType;
  }
};
</script>

<template>
  <SynVueButtonGroup>
    <SynVueTooltip content="Set sidenav to default">
      <SynVueIconButton
        :color="type === 'default' ? 'primary' : 'currentColor'"
        data-type="default"
        label="Set navigation to default"
        name="lunch_dining"
        size="small"
        @click="() => setType('default')"
      />
    </SynVueTooltip>
    <SynVueTooltip content="Set sidenav to rail">
      <SynVueIconButton
        :color="type === 'rail' ? 'primary' : 'currentColor'"
        data-type="rail"
        label="Set navigation to rail"
        name="space_dashboard"
        size="small"
        @click="() => setType('rail')"
      />
    </SynVueTooltip>
    <SynVueTooltip content="Set sidenav to sticky">
      <SynVueIconButton
        :color="type === 'sticky' ? 'primary' : 'currentColor'"
        data-type="sticky"
        label="Set navigation to sticky"
        name="preview"
        size="small"
        @click="() => setType('sticky')"
      />
    </SynVueTooltip>
  </SynVueButtonGroup>
</template>
