// packages/_private/vue-demo/src/AllComponents.vue
<script setup lang="ts">
import { SynVueTab, SynVueTabGroup, SynVueTabPanel } from '@synergy-design-system/vue';
import type { SynTabShowEvent } from '@synergy-design-system/components';
import * as DemoImports from './AllComponentParts/index.js';

const Demos = Object
  .entries(DemoImports)
  .map(([name, Component]) => [name.replace('Demo', ''), Component]);
const activeDemo = Demos.at(0)?.at(0);

const showTab = (e: SynTabShowEvent) => {
  const { name } = e.detail;
  (e.target as HTMLElement).parentElement?.scrollTo(0, 0);

  const dialog = document.querySelector('syn-dialog');
  if (dialog) {
    dialog.open = name === 'Dialog';
  }
};
</script>

<template>
  <SynVueTabGroup @syn-tab-show="showTab">
    <template
      v-for="([name, Component]) in Demos"
      :key="name"
    >
      <SynVueTab
        :active="name === activeDemo"
        :id="`tab-${name}`"
        :panel="name as string"
        slot="nav"
      >
        {{name}}
      </SynVueTab>
      <SynVueTabPanel
        :active="name === activeDemo"
        :name="name as string"
      >
        <div :id="`tab-content-${name}`" style="display: 'contents';">
          <component :is="Component" />
        </div>
      </SynVueTabPanel>
    </template>
  </SynVueTabGroup>
</template>

// packages/_private/angular-demo/src/allcomponents/allcomponents.component.ts
import { Component } from '@angular/core';
import { SynTabGroupComponent, SynTabComponent, SynTabPanelComponent } from '@synergy-design-system/angular';
import * as DemoImports from '../AllComponentParts/index.js';
import { CommonModule } from '@angular/common';
import { type SynTabShowEvent } from '@synergy-design-system/components';

const Demos = Object.entries(DemoImports);
const activeDemo = Demos.at(0)?.at(0);

@Component({
  selector: 'all-components',
  standalone: true,
  imports: [
    CommonModule,
    SynTabGroupComponent,
    SynTabComponent,
    SynTabPanelComponent,
  ],
  templateUrl: './allcomponents.component.html',
})
export class AllComponents {
  activeDemo: typeof activeDemo = activeDemo;
  Demos: typeof Demos = Demos;

  handleTabShow = (e: SynTabShowEvent) => {
    const { name } = e.detail;
    (e.target as HTMLElement).parentElement?.scrollTo(0, 0);

    const dialog = document.querySelector('syn-dialog');
    if (dialog) {
      dialog.open = name === 'Dialog';
    }
  }
}

<syn-tab-group
  (syn-tab-show)="handleTabShow($event)"
>
  @for (demo of Demos; track demo[0]) {
    <syn-tab
      [active]="demo[0] === activeDemo"
      [id]="'tab-' + demo[0]"
      [panel]="demo[0]"
      slot="nav"
    >
      {{demo[0]}}
    </syn-tab>
    <syn-tab-panel
      [active]="demo[0] === activeDemo"
      [name]="demo[0]"
    >
      <div [id]="'tab-content-' + demo[0]" style="display: contents;">
        <ng-container *ngComponentOutlet="demo[1]"></ng-container>
      </div>
    </syn-tab-panel>
  }
</syn-tab-group>
