// packages/_private/vue-demo/src/DemoFormValidate.vue
<script setup lang="ts">
import { ref } from 'vue';
import {
  SynVueAlert,
  SynVueButton,
  SynVueCombobox,
  SynVueCheckbox,
  SynVueDivider,
  SynVueFile,
  SynVueIcon,
  SynVueInput,
  SynVueOptgroup,
  SynVueOption,
  SynVueRadio,
  SynVueRange,
  SynVueRangeTick,
  SynVueRadioGroup,
  SynVueSelect,
  SynVueSwitch,
  SynVueTextarea,
  SynVueValidate,
} from '@synergy-design-system/vue';
import { highlightOptionRenderer, serialize } from '@synergy-design-system/components';
import {
  type FormStatus,
  currencyNumberFormatter,
  mockData,
  statusError,
  statusSuccess,
  statusWarning,
} from '@synergy-design-system/demo-utilities';
import DemoFieldset from './DemoFieldset.vue';

const nationalities = mockData('nationalities');

const testingFrameworks = mockData('testingFrameworks');

const initialFormData = mockData('initialValidateFormData');

const formData = ref({
  ...initialFormData,
});

const formStatus = ref<FormStatus>(statusWarning);

const formRef = ref<HTMLFormElement>();

// Custom formatter for donations
const formatter = currencyNumberFormatter;

const reset = () => {
  formStatus.value = statusWarning;
  formData.value = {
    ...initialFormData,
  };
}

const submit = (e: Event) => {
  e.preventDefault();
  e.stopPropagation();

  const formElement = e.target as HTMLFormElement;
  const isValid = formElement.checkValidity();

  formStatus.value = isValid ? statusSuccess : statusError;
}

const synChange = () => {
  const normalizedData = serialize(formRef.value!);

  // Log the normalized data
  console.log(normalizedData);
};
</script>

<template>
  <form
    @reset="reset"
    @submit="submit"
    @syn-change="synChange"
    ref="formRef"
  >
    <SynVueAlert
      v-if="formStatus.type !== 'warning'"
      class="form-validation-message"
      :open="true"
      :variant="formStatus.type"
    >
      <SynVueIcon slot="icon" :name="formStatus.icon" />
      {{ formStatus.message }}
    </SynVueAlert>

    <!-- PersonalInformation -->
    <DemoFieldset legend="Personal Information">

      <SynVueValidate variant="inline">
        <SynVueRadioGroup
          id="radiogroup-gender"
          name="gender"
          label="Please tell us your gender"
          required
          v-model="formData.gender"
        >
          <SynVueRadio value="">invalid</SynVueRadio>
          <SynVueRadio value="" readonly>invalid (readonly)</SynVueRadio>
          <SynVueRadio value="f">Female</SynVueRadio>
          <SynVueRadio value="m">Male</SynVueRadio>
          <SynVueRadio value="other">Other</SynVueRadio>
        </SynVueRadioGroup>
      </SynVueValidate>

      <SynVueValidate variant="inline">
        <SynVueSelect
          id="select-role"
          label="Current position"
          name="role"
          required
          v-model="formData.role"
        >
          <SynVueOption value="">---</SynVueOption>
          <SynVueOptgroup label="Developers">
            <SynVueOption value="backend">Backend Developer</SynVueOption>
            <SynVueOption value="frontend">Frontend Developer</SynVueOption>
          </SynVueOptgroup>
          <SynVueOptgroup label="Other">
            <SynVueOption value="lead">Team Lead</SynVueOption>
            <SynVueOption value="other">Other (please specify in comment section below)</SynVueOption>
          </SynVueOptgroup>
        </SynVueSelect>
      </SynVueValidate>

      <SynVueValidate variant="inline">
        <SynVueSelect
          id="select-previous-roles"
          label="Previous roles"
          name="previousRoles"
          multiple
          readonly
          required
          v-model="formData.previousRoles"
        >
          <SynVueOption value="">---</SynVueOption>
          <SynVueOptgroup label="Developers">
            <SynVueOption value="backend">Backend Developer</SynVueOption>
            <SynVueOption value="frontend">Frontend Developer</SynVueOption>
          </SynVueOptgroup>
          <SynVueOptgroup label="Other">
            <SynVueOption value="lead">Team Lead</SynVueOption>
            <SynVueOption value="other">Other (please specify in comment section below)</SynVueOption>
          </SynVueOptgroup>
        </SynVueSelect>
      </SynVueValidate>
    
      <SynVueValidate variant="inline">
        <SynVueInput
          id="input-text"
          label="Name"
          :minlength="5"
          :maxlength="20"
          name="name"
          placeholder="Please insert a value for the regular text input (between 5 and 20 Characters)"
          required
          v-model="formData.name"
          type="text"
        />
      </SynVueValidate>

      <SynVueValidate variant="inline" on="live">
        <SynVueInput
          id="input-email"
          label="E-Mail"
          name="email"
          placeholder="Please insert your E-mail address"
          required
          v-model="formData.email"
          type="email"
        />
      </SynVueValidate>

      <SynVueValidate variant="inline" on="input blur">
        <SynVueInput
          id="input-date"
          label="Date of birth"
          name="date"
          v-model="formData.date"
          type="date"
        />
      </SynVueValidate>

      <SynVueValidate variant="inline" on="live">
        <SynVueCombobox
          id="input-nationality"
          label="Nationality"
          name="nationality"
          required
          v-model="formData.nationality"
          ref="nationalityRef"
          :getOption="highlightOptionRenderer"
        >
          <SynVueOption v-for="nationality in nationalities" :key="nationality">
            {{ nationality }}
          </SynVueOption>
        </SynVueCombobox>
      </SynVueValidate>

    </DemoFieldset>
    <!-- /PersonalInformation -->

    <SynVueDivider />

    <!-- Security -->
    <DemoFieldset legend="Security">
      <SynVueValidate variant="inline" on="input blur">
        <SynVueInput
          id="input-password"
          label="Provide a secure password"
          name="password"
          password-toggle
          pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
          placeholder="Please provide at least one uppercase and lowercase letter and a number"
          required
          type="password"
          v-model="formData.password"
        />
      </SynVueValidate>

      <SynVueValidate variant="inline" on="input blur">
        <SynVueInput
          id="input-number"
          label="Please provide a fallback numeric value that may be used for password recovery"
          min="1000"
          max="9999"
          name="code"
          placeholder="Please choose a value with four digits, e.g. 1234"
          type="number"
          v-model="formData.code"
        />
      </SynVueValidate>
    </DemoFieldset>
    <!-- /Security -->

    <SynVueDivider />

    <!-- Topics -->
    <DemoFieldset legend="Topics">
      <SynVueSelect
        clearable
        id="topics"
        label="I am interested in the following technologies"
        multiple
        name="topics"
        v-model="formData.topics"
      >
        <SynVueOptgroup label="Frontend">
          <SynVueOption value="angular">Angular</SynVueOption>
          <SynVueOption value="react">React.js</SynVueOption>
          <SynVueOption value="vanilla">Vanilla.js</SynVueOption>
          <SynVueOption value="vue">Vue</SynVueOption>
        </SynVueOptgroup>
        <SynVueOptgroup label="Backend">
          <SynVueOption value="node">Node.js</SynVueOption>
          <SynVueOption value="Python">Python</SynVueOption>
        </SynVueOptgroup>
      </SynVueSelect>

      <SynVueCombobox
        id="testing-frameworks"
        label="Which testing frameworks do you use?"
        multiple
        name="testing"
        placeholder="Select testing frameworks"
        v-model="formData.testing"
        :getOption="highlightOptionRenderer"
        required
      >
        <SynVueOption v-for="framework in testingFrameworks" :key="framework.value" :value="framework.value">
          {{ framework.label }}
        </SynVueOption>
      </SynVueCombobox>
    </DemoFieldset>
    <!-- /Topics -->

    <SynVueDivider />

    <!-- Happiness -->
    <DemoFieldset id="happiness-fields" legend="Happiness">
      <SynVueValidate variant="inline" on="live">
        <SynVueRange
          id="happiness"
          label="How happy are you with the Synergy Design System?"
          :max="10"
          :min="0"
          name="happiness"
          v-model="formData.happiness"
        >
          <nav slot="ticks">
            <SynVueRangeTick>🤮</SynVueRangeTick>
            <SynVueRangeTick>🥱</SynVueRangeTick>
            <SynVueRangeTick>😍</SynVueRangeTick>
          </nav>
          <div slot="suffix">
            <SynVueInput
              name="happiness"
              type="number"
              v-model="formData.happiness"
              size="small"
              :min=0
              :max=10
            />
          </div>
        </SynVueRange>
      </SynVueValidate>

      <SynVueRange
        id="donations"
        label="I would donate between"
        :max="6000"
        :min="0"
        name="donations"
        :readonly="parseInt(formData.happiness!, 10) <= 5"
        v-model="formData.donations"
        restrict-movement
        :tooltipFormatter="(value: number) => formatter.format(value)"
      >
        <nav slot="ticks">
          <SynVueRangeTick>0 €</SynVueRangeTick>
          <SynVueRangeTick>6.000 €</SynVueRangeTick>
        </nav>
      </SynVueRange>
    </DemoFieldset>
    <!-- /.Happiness -->

    <SynVueDivider />

    <!-- Marketing -->
    <DemoFieldset legend="Please inform me about the following technologies">
      <SynVueValidate variant="inline">
        <SynVueCheckbox
          id="checkbox-newsletter-default"
          name="newsletterStandard"
          v-model="formData.newsletterStandard"
          required
        >
          Please subscribe me to the synergy newsletter
        </SynVueCheckbox>
      </SynVueValidate>
      <SynVueValidate variant="inline">
        <SynVueSwitch
          id="checkbox-newsletter-beta"
          name="newsletterBeta"
          v-model="formData.newsletterBeta"
          required
        >
          I am interested in the Synergy Beta Program
        </SynVueSwitch>
      </SynVueValidate>
    </DemoFieldset>
    <!-- /Marketing -->

    <SynVueDivider />

    <!-- AdditionalInformation -->
    <DemoFieldset legend="Additional Information">
      <SynVueValidate variant="inline" on="live">
        <SynVueTextarea
          id="additional-info"
          label="Comment"
          name="comment"
          placeholder="Please provide additional information that might be helpful for your inquiry"
          required
          :rows="10"
          v-model="formData.comment"
        />
      </SynVueValidate>
      <SynVueValidate variant="inline" on="live">
        <SynVueFile
          accept="image/*"
          droparea
          help-text="Please upload images only"
          id="screenshot"
          label="Optional Screenshot(s)"
          multiple
          name="files"
          v-model="formData.files"
        />
      </SynVueValidate>
    </DemoFieldset>
    <!-- /AdditionalInformation -->

    <SynVueDivider />

    <!-- Actions -->
    <div class="syn-submit-buttons">
      <SynVueButton variant="outline" type="reset">Reset</SynVueButton>
      <SynVueButton variant="filled" type="submit">Send</SynVueButton>
    </div>
    <!-- /Actions -->

  </form>
</template>

<style scoped>
form syn-divider {
  --spacing: var(--syn-spacing-2x-large);
}

form .syn-fieldset:last-of-type {
  margin-bottom: 0;
}

.syn-legend {
  font-size: var(--syn-font-size-large);
  margin-bottom: var(--syn-spacing-medium);
}

.syn-submit-buttons {
  align-items: center;
  border: none;
  display: flex;
  flex-direction: row;
  gap: var(--syn-spacing-large);
  margin: 0 0 var(--syn-spacing-2x-large) 0;
  padding: 0;
  justify-content: center;
}

/* Special overrides */
#happiness-fields syn-range nav {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

#radiogroup-gender::part(form-control-input) {
  display: flex;
  gap: var(--syn-spacing-medium);
}

#input-nationality::part(listbox) {
  max-height: min(var(--auto-size-available-height), 300px);
}
</style>

// packages/_private/angular-demo/src/demoformvalidate/demoformvalidate.component.ts
import type { SynChangeEvent } from '@synergy-design-system/components';
import { serialize } from '@synergy-design-system/components/utilities/form.js';
import { highlightOptionRenderer } from '@synergy-design-system/components/components/combobox/option-renderer.js';
import { Component, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import {
  type FormStatus,
  mockData,
  statusError,
  statusSuccess,
  statusWarning,
} from '@synergy-design-system/demo-utilities';
import { UsedSynergyComponentsModule } from '../modules/used-synergy.module';
import { DemoFieldSetModule } from '../modules/demofieldset.module';

const initialData = {
  ...mockData('initialValidateFormData'),
  // Custom test for angular validators
  email: ['', [
    Validators.required,
    Validators.email,
  ]],
};

@Component({
  selector: 'demo-form-validate',
  standalone: true,
  styleUrls: ['./demoformvalidate.component.css'],
  templateUrl: './demoformvalidate.component.html',
  imports: [
    UsedSynergyComponentsModule,
    DemoFieldSetModule,
    ReactiveFormsModule,
    CommonModule,
  ],
})
export class DemoFormValidate {

  @ViewChild('form') form!: ElementRef<HTMLFormElement>;

  formData!: FormGroup;

  formStatus: FormStatus = statusWarning;

  nationalities = mockData('nationalities');

  highlightOptionRenderer = highlightOptionRenderer;

  private _initFormData() {
    this.formData = this.fb.group({
      ...initialData,
    });
  }

  constructor(private fb: FormBuilder) {
    this._initFormData();
  }

  reset() {
    this.formStatus = statusWarning;
    this._initFormData();
  }

  validateEmailField() {
    const emailField = this.formData.get('email');
    const errors = emailField?.errors;

    // When the field is not changed, don´t show a message
    if (!emailField?.dirty) {
      return '';
    }

    if (!errors) {
      return '';
    }

    if (errors['required']) {
      return 'Email is required';
    }

    if (errors['email']) {
      return 'Invalid email';
    }

    return '';
  }

  submit(form: FormGroup) {
    const isValid = form.valid;
    this.formStatus = isValid ? statusSuccess : statusError;
  }

  synChange(_: SynChangeEvent) {
    const form = this.form.nativeElement;

    const normalizedData = serialize(form);

    // Log the normalized data
    console.log(normalizedData);
  }
}

<form
  enctype="multipart/form-data"
  [formGroup]="formData"
  (reset)="reset()"
  (ngSubmit)="submit(formData)"
  (syn-change)="synChange($event)"
  #form
  ngNativeValidate
>
  @if (formStatus.type !== 'warning') {
    <syn-alert
      class="form-validation-message"
      [open]="true"
      [variant]="formStatus.type"
    >
      <syn-icon slot="icon" [name]="formStatus.icon" />
      {{ formStatus.message }}
    </syn-alert>
  }

  <!-- PersonalInformation -->
  <demo-fieldset legend="Personal Information">

    <syn-validate variant="inline">
      <syn-radio-group
        formControlName="gender"
        id="radiogroup-gender"
        name="gender"
        label="Please tell us your gender"
        required
      >
        <syn-radio value="">invalid</syn-radio>
        <syn-radio value="" readonly>invalid (readonly)</syn-radio>
        <syn-radio value="f">Female</syn-radio>
        <syn-radio value="m">Male</syn-radio>
        <syn-radio value="other">Other</syn-radio>
      </syn-radio-group>
    </syn-validate>

    <syn-validate variant="inline">
      <syn-select
        formControlName="role"
        id="select-role"
        label="Current position"
        name="role"
        required
      >
        <syn-option value="">---</syn-option>
        <syn-optgroup label="Developers">
          <syn-option value="backend">Backend Developer</syn-option>
          <syn-option value="frontend">Frontend Developer</syn-option>
        </syn-optgroup>
        <syn-optgroup label="Other">
          <syn-option value="lead">Team Lead</syn-option>
          <syn-option value="other">Other (please specify in comment section below)</syn-option>
        </syn-optgroup>
      </syn-select>
    </syn-validate>

    <syn-validate variant="inline">
      <syn-select
        formControlName="previousRoles"
        id="select-previous-roles"
        label="Previous roles"
        name="previousRoles"
        readonly
        required
        multiple
      >
        <syn-option value="">---</syn-option>
        <syn-optgroup label="Developers">
          <syn-option value="backend">Backend Developer</syn-option>
          <syn-option value="frontend">Frontend Developer</syn-option>
        </syn-optgroup>
        <syn-optgroup label="Other">
          <syn-option value="lead">Team Lead</syn-option>
          <syn-option value="other">Other (please specify in comment section below)</syn-option>
        </syn-optgroup>
      </syn-select>
    </syn-validate>

    <syn-validate variant="inline">
      <syn-input
        formControlName="name"
        id="input-text"
        label="Name"
        [minlength]="5"
        [maxlength]="20"
        name="name"
        placeholder="Please insert a value for the regular text input (between 5 and 20 Characters)"
        required
        type="text"
      />
    </syn-validate>

    <syn-validate
      [customValidationMessage]="validateEmailField()"
      variant="inline"
      on="live"
    >
      <syn-input
        formControlName="email"
        id="input-email"
        label="E-Mail"
        name="email"
        placeholder="Please insert your E-mail address"
        required
        type="email"
      />
    </syn-validate>

    <syn-validate variant="inline" on="input blur">
      <syn-input
        formControlName="date"
        id="input-date"
        label="Date of birth"
        name="date"
        type="date"
      />
    </syn-validate>

    <syn-validate variant="inline" on="live">
      <syn-combobox
        formControlName="nationality"
        id="input-nationality"
        label="Nationality"
        name="nationality"
        required
        [getOption]="highlightOptionRenderer"
      >
        @for (nationality of nationalities; track nationality) {
          <syn-option>{{nationality}}</syn-option>
        }
      </syn-combobox>
    </syn-validate>

    <syn-validate variant="inline" on="live">
      <syn-combobox
        formControlName="previousNationality"
        id="input-previous-nationality"
        label="Previous Nationality"
        name="previousNationality"
        readonly
        required
        [getOption]="highlightOptionRenderer"
      >
        @for (nationality of nationalities; track nationality) {
          <syn-option>{{nationality}}</syn-option>
        }
      </syn-combobox>
    </syn-validate>

  </demo-fieldset>
  <!-- /PersonalInformation -->

  <syn-divider />

  <!-- Security -->
  <demo-fieldset legend="Security">
    <syn-validate variant="inline" on="input blur">
      <syn-input
        formControlName="password"
        id="input-password"
        label="Provide a secure password"
        name="password"
        password-toggle
        pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
        placeholder="Please provide at least one uppercase and lowercase letter and a number"
        required
        type="password"
      />
    </syn-validate>

    <syn-validate variant="inline" on="input blur">
      <syn-input
        formControlName="code"
        id="input-number"
        label="Please provide a fallback numeric value that may be used for password recovery"
        min="1000"
        max="9999"
        name="code"
        placeholder="Please choose a value with four digits, e.g. 1234"
        type="number"
      />
    </syn-validate>
  </demo-fieldset>
  <!-- /Security -->

   <syn-divider />

  <!-- Topics -->
  <demo-fieldset legend="Topics">
    <syn-select
      clearable
      formControlName="topics"
      id="topics"
      label="I am interested in the following technologies"
      multiple
      name="topics"
    >
      <syn-optgroup label="Frontend">
        <syn-option value="angular">Angular</syn-option>
        <syn-option value="react">React.js</syn-option>
        <syn-option value="vanilla">Vanilla.js</syn-option>
        <syn-option value="vue">Vue</syn-option>
      </syn-optgroup>
      <syn-optgroup label="Backend">
        <syn-option value="node">Node.js</syn-option>
        <syn-option value="Python">Python</syn-option>
      </syn-optgroup>
    </syn-select>

    <syn-combobox
      formControlName="testing"
      id="testing-frameworks"
      label="Which testing frameworks do you use?"
      multiple
      name="testing"
      placeholder="Select testing frameworks"
      [getOption]="highlightOptionRenderer"
      required
    >
      @for (framework of testingFrameworks; track framework.value) {
        <syn-option [value]="framework.value">{{framework.label}}</syn-option>
      }
    </syn-combobox>
  </demo-fieldset>
  <!-- /Topics -->

  <syn-divider />

  <!-- Happiness -->
  <demo-fieldset id="happiness-fields" legend="Happiness">
    <syn-validate variant="inline" on="live">
      <syn-range
        formControlName="happiness"
        id="happiness"
        label="How happy are you with the Synergy Design System?"
        [max]=10
        [min]=0
        name="happiness"
      >
        <nav slot="ticks">
          <syn-range-tick>🤮</syn-range-tick>
          <syn-range-tick>🥱</syn-range-tick>
          <syn-range-tick>😍</syn-range-tick>
        </nav>

        <div slot="suffix">
          <syn-input
            formControlName="happiness"
            type="number"
            size="small"
            [min]=0
            [max]=10
          />
        </div>
      </syn-range>
    </syn-validate>

    <syn-range
      formControlName="donations"
      id="donations"
      label="I would donate between"
      [max]="6000"
      [min]="0"
      name="donations"
      restrictMovement
      [readonly]="formData.get('happiness')?.value <= 5"
      [tooltipFormatter]="currencyFormatter"
    >
      <nav slot="ticks">
        <syn-range-tick>0 €</syn-range-tick>
        <syn-range-tick>6.000 €</syn-range-tick>
      </nav>
    </syn-range>

  </demo-fieldset>
  <!-- /.Happiness -->

  <syn-divider />

  <!-- Marketing -->
  <demo-fieldset legend="Please inform me about the following technologies">
    <syn-validate variant="inline">
      <syn-checkbox
        formControlName="newsletterStandard"
        id="checkbox-newsletter-default"
        name="newsletterStandard"
        required
      >
        Please subscribe me to the synergy newsletter
      </syn-checkbox>
    </syn-validate>
    <syn-validate variant="inline">
      <syn-switch
        formControlName="newsletterBeta"
        id="checkbox-newsletter-beta"
        name="newsletterBeta"
        required
      >
        I am interested in the Synergy Beta Program
      </syn-switch>
    </syn-validate>
  </demo-fieldset>
  <!-- /Marketing -->

  <syn-divider />

  <!-- AdditionalInformation -->
  <demo-fieldset legend="Additional Information">
    <syn-validate variant="inline" on="live">
      <syn-textarea
        id="additional-info"
        formControlName="comment"
        label="Comment"
        name="comment"
        placeholder="Please provide additional information that might be helpful for your inquiry"
        required
        [rows]="10"
      />
    </syn-validate>
    <syn-validate variant="inline" on="live">
      <syn-file
        accept="image/*"
        droparea
        formControlName="files"
        help-text="Please upload images only"
        id="screenshot"
        label="Optional Screenshot(s)"
        multiple
        name="files"
      />
    </syn-validate>
  </demo-fieldset>
  <!-- /AdditionalInformation -->

  <syn-divider />

  <!-- Actions -->
  <div class="syn-submit-buttons">
    <syn-button variant="outline" type="reset">Reset</syn-button>
    <syn-button variant="filled" type="submit">Send</syn-button>
  </div>
  <!-- /Actions -->

</form>
