// packages/_private/react-demo/src/ComplexBugs/Bug1304SingleDrawer.tsx
import type { SynDrawer } from '@synergy-design-system/components';
import { useRef } from 'react';

export const Bug1304SingleDrawer = () => {
  const drawerRef = useRef<SynDrawer>(null);

  const openDrawer = () => {
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    drawerRef.current?.show();
  };

  return (
    <>
      <syn-button data-testid="single-btn-1304" onClick={openDrawer}>Open Drawer</syn-button>
      <syn-drawer ref={drawerRef}>
        <div style={{ display: 'flex' }}>
          <syn-select data-testid="first"><syn-option value="1">Test 1</syn-option><syn-option value="2">Test 2</syn-option><syn-option value="3">Test 3</syn-option></syn-select>
          <syn-select data-testid="second"><syn-option value="1">Test 1</syn-option><syn-option value="2">Test 2</syn-option><syn-option value="3">Test 3</syn-option></syn-select>
          <syn-dropdown>
            <syn-button slot="trigger" caret>Dropdown</syn-button>
            <syn-menu>
              <syn-menu-item value="undo">Undo</syn-menu-item>
              <syn-menu-item>
                Find
                <syn-menu slot="submenu">
                  <syn-menu-item value="find-next">Find Previous</syn-menu-item>
                </syn-menu>
              </syn-menu-item>
            </syn-menu>
          </syn-dropdown>
        </div>
      </syn-drawer>
    </>
  );
};

// packages/_private/vue-demo/src/ComplexBugs/Bug1304SingleDrawer.vue
<script setup lang="ts">
import { SynVueButton, SynVueDrawer, SynVueSelect, SynVueOption, SynVueDropdown, SynVueMenu, SynVueMenuItem } from '@synergy-design-system/vue';
import { ref } from 'vue';

const drawerRef = ref<InstanceType<typeof SynVueDrawer>>();

const openDrawer = () => {
  drawerRef.value?.nativeElement?.show();
};
</script>

<template>
  <SynVueButton data-testid="single-btn-1304" @click="openDrawer">Open Drawer</SynVueButton>
  <SynVueDrawer ref="drawerRef">
    <div style="display: flex;">
      <SynVueSelect data-testid="first"><SynVueOption value="1">Test 1</SynVueOption><SynVueOption value="2">Test 2</SynVueOption><SynVueOption value="3">Test 3</SynVueOption></SynVueSelect>
      <SynVueSelect data-testid="second"><SynVueOption value="1">Test 1</SynVueOption><SynVueOption value="2">Test 2</SynVueOption><SynVueOption value="3">Test 3</SynVueOption></SynVueSelect>
      <SynVueDropdown>
        <SynVueButton slot="trigger" caret>Dropdown</SynVueButton>
        <SynVueMenu>
          <SynVueMenuItem value="undo">Undo</SynVueMenuItem>
          <SynVueMenuItem>
            Find
            <SynVueMenu slot="submenu">
              <SynVueMenuItem value="find-next">Find Previous</SynVueMenuItem>
            </SynVueMenu>
          </SynVueMenuItem>
        </SynVueMenu>
      </SynVueDropdown>
    </div>
  </SynVueDrawer>
</template>
